### ISSUE TITLE
When GNOME is using dark mode, Cawbird can't

### ISSUE THREAD

**Issue by spacebug0** [IBBoard/cawbird#134]
**Describe the bug**
When I set GNOME to use Dark mode ("Adwaita-dark" theme), Cawbird switches to light theme.
No matter how I flip the dark mode button in Cawbird it stays in light theme.

**To Reproduce**
1. Run Debian 10 with GNOME (in Wayland session).
2. Install Cawbird from flatpak.
3. Set Cawbird to use dark mode.
4. Open GNOME tweek tool and set theme to "Adwaita-dark"
5. Cawbird now changes to light theme (though the button stays set to dark mode)
6. Try changing the dak mode button in Cawbird and see that the theme does not change from light mode no matter what.

**Expected behavior**
Cawbird should not change from it's dark mode

**System details:**
 - OS: Debian 10 64bit with GNOME in Wayland session
 - Version: 1.0.5
 - Package type:Flatpak

**Comment by IBBoard** [comment]
The "dark theme" switch switches to the dark variant, if the theme has it.

I suspect this is a Flatpak issue. I think I've read things about Flatpak not honouring themes before, because of the way it (intentionally) 'sandboxes' itself.

I don't have a clue about Flatpak. Hopefully @p1u3o or someone else with more experience has some ideas.

**Comment by p1u3o** [comment]
Does it make any difference if you install the `org.gtk.Gtk3theme.Adwaita-dark` flatpak package?

You'll need to restart Cawbird after installing it.

**Comment by spacebug0** [comment]
Installing `org.gtk.Gtk3theme.Adwaita-dark` fixed it

**Comment by p1u3o** [comment]
Great. `flatpak update` should automatically pull that in if you set it as the system style.
