### ISSUE TITLE
Feature request: trends and threads

### ISSUE THREAD

**Issue by ebeyer** [IBBoard/cawbird#139]
**Is your feature request related to a problem? Please describe.**
My usual workflow with twitter on a browser is to scan trending topics and click on those that interest me.  It seems one can't do this in cawbird, as it stands.

Often when scanning my twitter timeline on a browser, I like to open an individual tweet and follow the writer's thread.  Sometimes these are 'tweet storms' of 3 to 20+ tweets.  This does not appear to be possible in cawbird, as it stands.

**Describe the solution you'd like**
It would be great if there was a button on cawbird that would list trending topics or hashtags that I could click and open in a new window (eg., #FAMOUSPERSON_SAYS_SILLY_THING).

It would also be great if threads of tweets could be opened easily in cawbird (eg., "Longish tweet 1/x") so I can read the whole thread.
  
**Describe alternatives you've considered**
I could just keep reading twitter on Chrome, but that's boring!

**Additional context**
Great work so far.  Thank you for your time and work.

**Comment by IBBoard** [comment]
Please only request one feature or report one bug per issue, otherwise we can't track and resolve things.

An approximation of threads should already be happening under #17, although we're constrained by the limitations of the Twitter API (see the "[limitations](https://github.com/IBBoard/cawbird#limitations)" section of the README)

Opening hashtags is already possible and it'll do a search for them.

Trending topics is possible in theory because [there's an API for it](https://developer.twitter.com/en/docs/trends/trends-for-location/api-reference/get-trends-place), but we'd need to know a location to look up and find a way to integrate it with the UI when we've already got too many tabs and are trying to reduce them.

Opening anything in a new window is a completely separate issue again. Cawbird's design is single-column, single-window at the moment. Anything else needs a significant overhaul in the UI. It's more likely (but still much lower priority, due to the work needed and the other priorities) that we go multi-column.

**Comment by ebeyer** [comment]
Thank you for the timely and detailed reply.

With respect,
==================
Eric L Beyer 
eric@beyer.bz
