### ISSUE TITLE
Allow unauthenticated use

### ISSUE THREAD

**Issue by nidico** [IBBoard/cawbird#146]
If you just intend to *read* twitter and do not plan to actively interact, authentication is not required and should therefore also not be required by the app (if this is possible).

Of course this would avoid a whole set of privacy and security issues for those users and also allows usage by users who do not want or cannot create a twitter acount.

Is there a technical requirement for authentication by the twitter "not-api", e.g. in order to create a session, or is this "just not implemented"?

**Comment by IBBoard** [comment]
Twitter's API needs authentication tokens so that it can rate limit you (so that people don't write scripts to abuse the servers, or users). There is an "application authentication" mode, but my understanding is that it rate limits the application as a whole, not just your install. That means that the few hundred requests that Cawbird's key is allowed to use would be consumed by every user who uses that mode, meaning that they could all be consumed by one abusive user.

Also, there wouldn't be a home timeline to show (because you've not got an account, so you can't follow people) so I don't see how it'd work and it doesn't fit with how a Twitter client is generally architected.

**Comment by nidico** [comment]
Thanks for the quick answer!

> Twitter's API needs authentication tokens so that it can rate limit you (so that people don't write scripts to abuse the servers, or users). There is an "application authentication" mode, but my understanding is that it rate limits the application as a whole, not just your install.

That's a pity - I was afraid that there was some limitation... I also read [the corresponding documentation](https://developer.twitter.com/en/docs/basics/rate-limiting) the same way.

> Also, there wouldn't be a home timeline to show (because you've not got an account, so you can't follow people) so I don't see how it'd work and it doesn't fit with how a Twitter client is generally architected.

Without giving too much thought: I would strip the "unauthenticated mode" interface considerably, e.g. mainly keep search and maybe add a "last visited users / searches" list or a locally maintained list of users / searches. Maybe this would be more of a twitter browser than a typical twitter client.

Anyway, due to the limitations this won't happen anyway so I'm closing the request.
