### ISSUE TITLE
Use Twitter app protocol instead of API (and add missing features)

### ISSUE THREAD

**Issue by luke-jr** [IBBoard/cawbird#150]
Is there any reason Cawbird *needs* to use the official Twitter API?
Why not just reverse-engineer the interface their own apps use?

**Comment by IBBoard** [comment]
The bit where they provide an API for third-parties to use and the [Twitter Terms of Use](https://twitter.com/en/tos) specifically forbid scraping the website using automated means suggests that they really wouldn't look kindly on any app that pretends to be the official app!

**Comment by luke-jr** [comment]
Using an undocumented API isn't really scraping...

Besides, does it really matter how kindly they do or don't look on the app?

**Comment by IBBoard** [comment]
No, is not scraping. But when they have an API and tell people not to scrape the website then it's clear that they want all third-party apps to use the API.


As for whether it matters, that depends on whether you think "Cawbird gets blacklisted/served a DMCA takedown notice" and "Cawbird regularly breaks because it relies on an undocumented API that changed unexpectedly in undocumented ways" matters.
