### ISSUE TITLE
Threading UI: indicate existence of previous post in thread

### ISSUE THREAD

**Issue by schmittlauch** [IBBoard/cawbird#158]
**Is your feature request related to a problem? Please describe.**

When clicking on a tweet that is part of a thread/ reply chain and that has predecessor tweets, these are rendered above it. But directly after clicking, the scroll position aligns with the top of that tweet, hiding all potentially existing predecessors.

**Describe the solution you'd like**
The existence of predecessor tweets needs to be indicated somehow.
One option is to change the initial scroll position such that the lower half of the predecessor tweet is revealed.
Another option is adding a small color bar, arrow or another hint at the top of the tweet.

**Comment by IBBoard** [comment]
The old design had a theme-coloured bar (so blue under Adwaita) at the top to 'show' that there was more up there. It's not a pattern that I've ever seen anywhere else, and IIRC it took me months before I actually noticed it.

I removed it in the new design because a) it's not clear, b) the tweet you've clicked from has the "reply" icon on the right-hand side and c) it should already say "reply to [previous person]" when it's a reply.

I've looked at Twitter and they drop you on the tweet with no clear marker that there's anything above. (Not that Twitter design is perfect, but it's a reference point).

I've looked in Cawbird and I've noticed that it doesn't do "Replying to" when it's a self-reply, so there are some situations that aren't as obvious.

Showing some of the previous tweet would be trivial, but I'm concerned it might look like a rendering issue.

I think we need some design ideas and feedback on what works for people.

**Comment by IBBoard** [comment]
I've changed the "Replying to" logic in the Tweet Info View so that it now indicates a self-reply. Does that work for the situations you were thinking of?

![Screenshot from 2020-06-13 11-43-04](https://user-images.githubusercontent.com/388582/84566730-5d800b80-ad6b-11ea-9ff4-74448f2fa81a.png)
![Screenshot from 2020-06-13 11-43-08](https://user-images.githubusercontent.com/388582/84566729-5ce77500-ad6b-11ea-8c47-16aef74b6811.png)

The only other thing I've considered is a Twitter-like "thread line", but a) I don't know how to do that and b) it'll be okay in the threads (where there's a margin to put it in) but not in the main tweet.

If anyone wants to sketch a mockup proposal then go for it!

**Comment by schmittlauch** [comment]
Thanks.
