### ISSUE TITLE
«translate content» button

### ISSUE THREAD

**Issue by tassoman** [IBBoard/cawbird#161]
I use to follow people from different countries, so that I feel would be useful having a «translate» button near the tweet item actions.

Because of privacy concerns, automatic posting content to google translate is a «no good» feature.
So I suggest to put a button link who open the default browser at:
```https://translate.google.com/?op=translate&sl=auto&tl={UI_LANG}&text={CONTENT}```

**Comment by IBBoard** [comment]
Interesting idea, and I agree that we don't want everything auto-posting to Google. I'm not entirely convinced we'd want to link it to Google, though. It would be nice if there was a better, FOSS-friendly solution.

For now, every tweet has a link and you can click on that to open it in a browser and then translate it there.

**Comment by CodedOre** [comment]
There would be a possible OSS offline translation tool we might be able to use. 

Haven't checked it in detail for now though.

https://github.com/argosopentech/argos-translate

**Comment by IBBoard** [comment]
We don't have to do offline translation (in fact, that's probably hugely limiting, because it requires people to install translation packs locally) but that's a good starting point.

It looks like they use [OpenNMT](https://opennmt.net/) and I'm trying to work out what ArgosTranslate adds on top (other than pre-trained models).

But more importantly, they link to [LibreTranslate](https://libretranslate.com/), which appears to offer a free web service with an API that we could use. It doesn't appear to require authentication, it lists itself as "Free and open source" and I can't see any usage constraints. We're unlikely to be hitting the API that often either. But I'll poke it a bit more to see whether that's supposed to be a demo rather than an API (even though it's on a dedicated domain, which implies it's a service)

**Comment by IBBoard** [comment]
> The web service is currently for demo (we'd prefer people not use it for production environments). You will also be rate limited after ~20 requests / minute. We are currently planning to release a paid plan for $100 / year for production use (which should be cheaper than running your own cloud machine). 

So, LibreTranslate is an option *but* we'd need a way to fund the $100/y infrastructure costs.

Otherwise we would need to look at how Argostranslate might integrate with a Vala app and force people to download dictionaries/language models. Or we find another library/service.

**Comment by tassoman** [comment]
In my opinion, founding an infrastructure sounds a little bit complicated for a not core feature.
Maybe the Libretranslate instance can be packed with the client, and instanced during main process boot, listening just on localhost.
I dunno how much it would bloat the actual cawbird client software base

**Comment by CodedOre** [comment]
Then it would make more sense to just use Argostranslate. Setting up an server on your PC just for translation is overkill.

But I think it could work with Argos.

The biggest challenge would probably be packaging, as it is currently only distributed over pip, so we probably need to create a packaged version of it.
Packaging with Flatpak will most likely be the simplest implementation, as there it would just be a module.

As for the language packs, if they are under the same license, we could just distribute them with the Argos package or module.
Might be good to ask that.

I think Argos might be a good solution, but we need to take a deeper look before saying anything.

**Comment by IBBoard** [comment]
If there's not a public server that we can use then we definitely need to make it 100% pluggable. As the model for each language pair is 84MB then that's going to be a *huge* increase over the ~500KB package (plus ~100KB of translations) that we currently ship! Given that most people won't use most language packs (if any), and 84MB is quite a lot to load on many connections then we need to make people aware of what can be done and how long it would take to add more languages.

Also, we're native-first, so even if we can make a monster-sized Flatpak build that bundles Argostranslate and all of its requirements ([including PyQt](https://github.com/argosopentech/argos-translate/blob/master/requirements.txt), for some reason) *and* all of the common translation packs (with a way to add more to a Flatpak) then we still need to understand how that happens when someone installs it from the Fedora official repositories, for example.

Out of interest, I also took a look at Google's API and the pricing for that is unsurprisingly variable - https://cloud.google.com/translate/pricing - first 500K characters (so about 2000 tweets) for "free" then $20 per million characters.

**Comment by CodedOre** [comment]
Well, did not looked on the size of the translations models...
Then this is probably not the most viable option.

So, it is basically back to using an online service again. My question would still be: would 2000 translated tweets be enough for any user, or would we need to pay at some point anyway? And it would still be Google then...

But looking at the pricing the seem to have a similar pricing to [DeepL](https://www.deepl.com/pro#developer), a german based translator with better translations, so if we would already raise money for translation support that might be an alternative (basically because it is not Google).

**Comment by IBBoard** [comment]
I had an "idea" that I think is the best compromise, and I've just noticed that it falls back to @tassoman's original approach - link to a translation service. If we template it then we can let people pick other services. And because it's opening a website in the default browser then it's no different to the user opening a browser and copying and pasting the text.

I was hoping we could integrate it in-line (like Twitter web does) but it's not looking feasible or cost-effective.

**Comment by philipzae** [comment]
Was just going to file a bug report on this same thing, as i couldn't read this [cawbird quoted retweet](https://twitter.com/CawbirdClient/status/1349452474063724545). I utilize microsoft's translation in tweetdeck and google's translation on twitter.com, but also the [Translator](https://translator.sailormax.net/cabinet/) browser extension which allow you to pick which provider you'd like to use.

@tassoman's approach is the best option at the moment, as I would prefer not to go to twitter's website if i'm using cawbird and not have to go through a second step to do the translation. Which translator provider could be set in the settings dialog. I would suggest having google, microsoft, and deepl (popular with japanese twitter users).

https://www.bing.com/translator/?to={UI_LANG}&text={CONTENT}
https://www.deepl.com/translator#auto/{UI_LANG}/{CONTENT}

**Comment by IBBoard** [comment]
Twitter tells us the (guessed) language for each tweet. We should probably trust that as a starting point. Bing and Google seem to use `from=…` in the query string while Deepl needs the 'auto' replaced.

I'm not planning to put a "translate to" option in to Cawbird. I `$LANG` *should* give us the user's default language (e.g. mine is `en_GB.UTF-8`) and if we get `C` then we should probably assume English. We will definitely need to trim everything after the dot, and we might need to trim the underscore as well.

**Comment by tassoman** [comment]
Hello there, thanks you for joining me in the insight. My opening comment was for a mockup like this

![mockup-lang-cawbird](https://user-images.githubusercontent.com/92727/104655031-5d5b3c00-56bd-11eb-8ced-22fc1a743e16.png)

The link should open the browser in the chosen translation service, as you stated before It's like cut-n-pasting. If the content is coming from a public profile, there's no trouble submitting the content. (maybe you can just permit public posts translation)

I think is the thinner implementation, just a UI modificaiton and a few events

**Comment by philipzae** [comment]
> Twitter tells us the (guessed) language for each tweet. We should probably trust that as a starting point. Bing and Google seem to use `from=…` in the query string while Deepl needs the 'auto' replaced.

There wasn't a from argument in the Bing link I shared and I substituted the auto generated language code with 'auto' for the DeepL link, which it replaces once you arrive at the page.

> I'm not planning to put a "translate to" option in to Cawbird.

@tassoman's mockup seems like a suitable spot to put a translation button or alternatively at the end of the tweet's text, a localized '[translate]' text could be put.

> I think `$LANG` _should_ give us the user's default language (e.g. mine is `en_GB.UTF-8`) and if we get `C` then we should probably assume English. We will definitely need to trim everything after the dot, and we might need to trim the underscore as well.

Definitely sounds good to me of the trimming the dot and underscore, as none of the services use localized version of a language.

@tassoman: regarding your mockup, likely the text should be changed from 'Would you like to translate?' to 'Select translation provider' and i think we can get rid of the 'never ask me again' checkbox.

**Comment by tassoman** [comment]
To me would be fine as first iteration. Then you can collect users feedback about this and go on further fine tuning this useful feature 💯

**Comment by CodedOre** [comment]
I would not add this dialog in the tweet detail view. A button leading to a translator is fine for me, but I would argue the popup would be bad design, especially since this is something you would only select once...

If we want to add different translation options, I would put the selection inside the settings.

**Comment by tassoman** [comment]
I agree, my initial UI hypothesis may bloat the wall with a secondary feature. Maybe it can be triggered with a "Translate" menu item inside the functions menu, just before "Other" menu?   
The key is having a fast way to read a translated content.

:repeat:  :heart:  :leftwards_arrow_with_hook: :new:  :arrow_down: 

![Istantanea_2021-01-15_16-16-41](https://user-images.githubusercontent.com/92727/104744451-2f253d00-574d-11eb-9a50-79186dde7267.png)

**Comment by CodedOre** [comment]
So, I have designed a few prototypes with my prototype project.

What I personally would have in mind would be a translate button in the secondary menu of the detail view and the options in the settings:

<a href="translator-menu"><img src="https://user-images.githubusercontent.com/47981497/104756306-ef198680-575b-11eb-92e9-ebb3ec7fbba4.png" height="60%" width="60%" ></a>   <a href="translator-options"><img src="https://user-images.githubusercontent.com/47981497/104756372-048eb080-575c-11eb-9237-240bb069001b.png" height="35%" width="35%" ></a>



Additional we can add an Button where like, retweet and reply are:

<a href="translator-button"><img src="https://user-images.githubusercontent.com/47981497/104756923-b75f0e80-575c-11eb-9a74-462cc1b63def.png" height="80%" width="80%" ></a>



And finally your suggestion, having the selection as a popup when clicking the button:

<a href="translator-inner-menu"><img src="https://user-images.githubusercontent.com/47981497/104756924-b7f7a500-575c-11eb-9b16-4f8f16a29d10.png" height="80%" width="80%" ></a>

However, I would say this has not real benefit. It is unlikely a user will often change the translation service and then we could avoid the second click by just going to the translation.

**Comment by IBBoard** [comment]
> There wasn't a from argument in the Bing link I shared and I substituted the auto generated language code with 'auto' for the DeepL link, which it replaces once you arrive at the page.

Yeah, but I checked the services to see how they handle specific "from" languages, because we know what Twitter says they are and so it is useful if we specify that.

> If we want to add different translation options, I would put the selection inside the settings.

Agreed. Most people won't want to swap translation service on each and every click, so we'll make it a setting.

> What I personally would have in mind would be a translate button in the secondary menu of the detail view and the options in the settings:
> 
> [<img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/47981497/104756306-ef198680-575b-11eb-92e9-ebb3ec7fbba4.png">](translator-menu) [<img alt="" width="35%" height="35%" src="https://user-images.githubusercontent.com/47981497/104756372-048eb080-575c-11eb-9237-240bb069001b.png">](translator-options)

The settings are fine, but I'm not sure that the button and menu has enough context to tie it to the main tweet rather than translating everything in that view.

Also, we might want to have the settings let people use other services as well (e.g. a local LibreTranslate server). Initially I'll probably make that a "hidden" setting, though - if you edit it in GSettings then you can put in your own service with placeholders, but if you break the translation links then that's your problem!)

> Additional we can add an Button where like, retweet and reply are:
> 
> [<img alt="" width="80%" height="80%" src="https://user-images.githubusercontent.com/47981497/104756923-b75f0e80-575c-11eb-9a74-462cc1b63def.png">](translator-button)

I'm not sure that the book is the right icon, but that positioning is probably better than putting it with the RTed/Liked/Reply icons, which are a bit small in the timeline. Is there a universal or standard "translate" icon? And would we want the two-letter ISO country code or would that be meaningless to most people?

> Maybe it can be triggered with a "Translate" menu item inside the functions menu, just before "Other" menu?
> The key is having a fast way to read a translated content.
> 
> ![Istantanea_2021-01-15_16-16-41](https://user-images.githubusercontent.com/92727/104744451-2f253d00-574d-11eb-9a50-79186dde7267.png)


I'm currently planning to do the translation link like Twitter does - in the tweet detail view. I was wondering where we might fit a translation button in a timeline as well. But this seems to work.

**Comment by philipzae** [comment]
> I'm not sure that the book is the right icon, but that positioning is probably better than putting it with the RTed/Liked/Reply icons, which are a bit small in the timeline. Is there a universal or standard "translate" icon? And would we want the two-letter ISO country code or would that be meaningless to most people?

I haven't seen a universal/standard translate icon and with the icon being so small, there is no way to effectively give a suitable icon metaphor for it, so the book/dictionary icon does seem reasonable and with the language code beside it, it does do a good job at trying to represent it.

> I'm currently planning to do the translation link like Twitter does - in the tweet detail view. I was wondering where we might fit a translation button in a timeline as well. But this seems to work.

For timeline view, i'll prepare some mockups.

**Comment by CodedOre** [comment]
> The settings are fine, but I'm not sure that the button and menu has enough context to tie it to the main tweet rather than translating everything in that view.

That is a good point. Since the menu is still relevant (for some other options), we could then move it inside the tweet box:

![menu-moved](https://user-images.githubusercontent.com/47981497/104774745-82ac8080-5777-11eb-9d65-24d25251a6a8.png)

> I'm not sure that the book is the right icon, but that positioning is probably better than putting it with the RTed/Liked/Reply icons, which are a bit small in the timeline. Is there a universal or standard "translate" icon? And would we want the two-letter ISO country code or would that be meaningless to most people?

Don't know about an good icon. For now I used the dictionary, as it is the best from the default set.

If we want the button there, it might be a good idea to create a better one though.

**Comment by philipzae** [comment]
Two possible places to put the translation link. Either underneath the tweet, similar to the retweet line below the tweet, or when clicking on the 'Open in Browser' link which would then show a popup.
![image](https://user-images.githubusercontent.com/4412114/104776328-556dcb80-5793-11eb-93f4-1f75cfbf75b4.png)

**Comment by tassoman** [comment]
actually the most used metaphor is latin vs kanji
https://origin.fontawesome.com/icons/language?style=regular
https://fontawesome.com/v4.7.0/icon/language

**Comment by IBBoard** [comment]
> That is a good point. Since the menu is still relevant (for some other options), we could then move it inside the tweet box:

It puts a bit more content inside each box, but I think it's the right way to do it. And the kebab is reasonably unintrusive when you're not hovering over it.

> actually the most used metaphor is latin vs kanji

Yes, that's what I thought I'd seen. But I didn't have time to dig out icons, or check what Gnome uses (if anything). I know "Internationalisation" is a green and a purple flag in Gnome, but that's a) not obvious for this context and b) more about whether you use commas or fullstops as your decimal point.

> Two possible places to put the translation link. Either underneath the tweet, similar to the retweet line below the tweet, or when clicking on the 'Open in Browser' link which would then show a popup.

I don't think there's any harm in adding it under the menu. Putting it below the text would be easier for people to discover, but is probably too visually noisy for the main timeline. It was how I planned to do it for the Tweet Info view, though.

I was going to say something about the difficulty of having "Translate to English" in terms of populating translations, but I think that's actually going to be the easier way to do it! You only need one translation string for the current language, which is "Translate to <your language>" where the English has "Translate to English", the French has "Traduire en français" (or so Google Translate tells me!), etc.

That's *much* easier than getting every translator to translate [every language's name](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) into their own language and trying to write "Translate from <source-language>"! (i.e. mapping "en" to "English" in English, "l'Anglais" in French, and then "fr" to "French"/"Français", etc and putting the appropriate one into the translation)

.

@CodedOre How difficult would it be in the libhandy UI to have a None/Google/Bing/DeepL/Custom selection and then a text box for a URL?

**Comment by CodedOre** [comment]
> @CodedOre How difficult would it be in the libhandy UI to have a None/Google/Bing/DeepL/Custom selection and then a text box for a URL?

Would be fairly easy to do:

![inline-setting](https://user-images.githubusercontent.com/47981497/104811191-3ce4cc00-57fa-11eb-9c6f-f8a5ce1b82cc.png)

**Comment by IBBoard** [comment]
How would that do on mobile screens? Can we make the text box drop underneath, or is that radio button list fixed height?

The alternative might be that the text box is a separate control, changing the list selection enables/disables the textbox, and we fill in the Google URLs when they pick "Google" etc.

**Comment by CodedOre** [comment]
> How would that do on mobile screens? Can we make the text box drop underneath, or is that radio button list fixed height?
>
> The alternative might be that the text box is a separate control, changing the list selection enables/disables the textbox, and we fill in the Google URLs when they pick "Google" etc.

`HdyActionRow` only allows for widget to be in own row. But this can be circumvented by either using an `HdyExpanderRow: 

![settings-expanded](https://user-images.githubusercontent.com/47981497/104811681-81259b80-57fd-11eb-82c8-0e24a9fc0ba4.png)

or by creating the content by ourselves:

![mobile-translator](https://user-images.githubusercontent.com/47981497/104812108-5721a880-5800-11eb-82d1-6426e0617a1a.png)

Here I used an `GtkGrid` inside an `HdyPreferencesRow` and placed the items manually. This has the drawback of not longer be showing up in the search though.

**Comment by IBBoard** [comment]
> `HdyActionRow` only allows for widget to be in own row. But this can be circumvented by either using an `HdyExpanderRow`:

How does that look when not expanded? Presumably it looks like part of the list (like the other entries, but with a drop-down arrow)?

**Comment by CodedOre** [comment]
> How does that look when not expanded? Presumably it looks like part of the list (like the other entries, but with a drop-down arrow)?

That's right.

**Comment by IBBoard** [comment]
Rough-and-ready first implementation in the Tweet Info view. Still a lot of tidying up and creation of settings to do.

![Screenshot from 2021-01-16 20-59-26](https://user-images.githubusercontent.com/388582/104822879-ba7dfb80-583d-11eb-9d91-daac72ed0ca5.png)

**Comment by philipzae** [comment]
Might be better to put it above the photo, as that is where people's eyes would be after being unable to read the foreign text.

**Comment by IBBoard** [comment]
Good point. I'll fix that later.

**Comment by IBBoard** [comment]
We should now have Translate in the TweetInfo view and in the menu for all tweet lists (home timeline etc). But it is still hard-coded to Google for now. Making it a setting is the next step.

**Comment by tassoman** [comment]
If you think it's useful and can be done, would be nice to translate  only public content (public timelines), or maybe let the user check in the settings "translate private tweets also" 🤔

**Comment by IBBoard** [comment]
Is that useful? I can see half an argument for "it's a tweet from a private account, so we don't want to leak the content that's otherwise private". But if you can't read the languages then you can't understand the tweet and so all that removing the translation option does is mean that people will copy and paste the text manually.

Would we be better with a "this tweet is private, are you sure?" prompt? Which way would be clearer and less annoying?

Or maybe allow translating private tweets but prompt by default and then the setting is "never ask"?

**Comment by philipzae** [comment]
If a tweet or DM is private on twitter and it gets translated by microsoft or google, you don't get prompted about it being private, so don't believe a prompt is needed in cawbird.

**Comment by tassoman** [comment]
I've said that because I don't know your policy on data privacy, but if you're fine with that and want to spare some nagging, I agree with you can be clumsy.

**Comment by philipzae** [comment]
I guess if we want to more privacy cautious, we can do the prompt for private tweets and DMs with the 'never ask again' checkbox.

@IBBoard does the API notify of which tweets are private?

**Comment by IBBoard** [comment]
> @IBBoard does the API notify of which tweets are private?

Tweets have user profiles. User profiles have a "protected" flag. That's the only way to make it private.

I'm happier leaving "translate protected tweet" as an available action that requires user interaction (where people are still broadcasting to some subset of users) than I am with the idea of implementing the translation function for DMs (which are literally private, one-to-one conversations)

**Comment by IBBoard** [comment]
Okay, I think I'm about done with this now. We've got settings. We've got validation of custom settings. And we've got both "Translate to <my language>" in the TweetInfo view and a "Translate" option in the right-click > more actions menu.

Can anyone think of anything I missed?

**Comment by philipzae** [comment]
Was curious why it has to be under the more actions menu, or anything has to be under there, as there is alot of space and 2 clicks are better than 3.

**Comment by IBBoard** [comment]
The available buttons are the standard Twitter actions. Everything that's non-standard (or dangerous) is under the menu.

But unlike Twitter, we have one menu instead of two (the meatball menu top-left and the weird "could be an upload file icon" menu beside the Reply/RT/Like buttons)

There could be enough space for them all to be displayed, but then we'll hit a point where it impacts narrow displays. And we'd have to think of a clean, simple icon for each one that clearly conveys its meaning on its own so that it doesn't look cluttered/out of place. And they'd need a colour.

**Comment by tassoman** [comment]
As far I can understand, the feature can be triggered in two ways: "Translate button inside TweetInfo view" (I bet it's a brick of the timeline wall), and actions menu, right clicking the tweet. I think it can greet everyone...
In my installation, the actions menu is the only way to interact with the tweet (xubuntu xfce 20.04)
I haz no burgers menu, kepapz eizer :cat2:

**Comment by IBBoard** [comment]
"Tweet Info view" is when you click/double-click (depending on settings) the tweet to view it with replies. For those tweets, it will show below the text but above the images.

Twitter is the one with with the "[meatball menu](https://www.reddit.com/r/Design/comments/8856ft/from_an_ux_standpoint_what_are_the_different/)". We have no foodstuffs.

**Comment by philipzae** [comment]
> The available buttons are the standard Twitter actions. Everything that's non-standard (or dangerous) is under the menu.

Quote retweet is a standard twitter action now as its under the retweet icon, but not sure why you'd want to be limited to only show the default twitter actions, when it only decreases the user experience.

**Comment by philipzae** [comment]
Forgot to mention that I found another place translate should be. In the text select context menu.

**Comment by tassoman** [comment]
At minimum window size, I feel there's no more room for tweet action buttons. I agree translation feature isn't a core first class feature for tweet interaction.

![Istantanea_2021-01-29_08-13-19](https://user-images.githubusercontent.com/92727/106243630-05b6e780-620a-11eb-90f6-12434d523cbe.png)

**Comment by tassoman** [comment]
I dunno if graphic library permits but numbers and buttons, maybe they can be combined to save more space

This is an example mock-up. But I think it's off-topic.
![actions-mock](https://user-images.githubusercontent.com/92727/106244834-d1442b00-620b-11eb-9b13-0c8cb07531e3.png)

**Comment by philipzae** [comment]
Guess we are misunderstanding each other, as I was speaking about the timeline, which has alot of empty space.

![image](https://user-images.githubusercontent.com/4412114/106307672-105c9580-6279-11eb-8cbe-b9d1f11da99a.png)

**Comment by IBBoard** [comment]
> Quote retweet is a standard twitter action now as its under the retweet icon

For a given value of "standard". It's still just three buttons for the main three actions. But one now has options

> but not sure why you'd want to be limited to only show the default twitter actions, when it only decreases the user experience.

Because overloading the user with too many buttons at once, especially when their icons are unclear, also decreases the user experience.

> Forgot to mention that I found another place translate should be. In the text select context menu.

Maybe. But you're only going to be doing that from Tweet Info pages, which have a "Translate" link anyway. Or you're trying to handle the "someone used mixed text that didn't get picked up as needing translation and so I only want to translate part of it" use case, in which case a) most users would be selecting for other reasons and would see "Translate" for their own language and b) we don't have a source language so we're going to be using "auto" mode, which isn't as reliable. And c) we don't want to imply that we will let them translate to an arbitrary language (e.g. selecting native text and expecting to translate it to a foreign language).

I'm inclined to leave that as "the user can copy and paste the text, the same as they could in other apps".

> I dunno if graphic library permits numbers and buttons being combined to save more space

We can put (almost) anything in widgets, so we probably could combine it like Twitter does. But I think that grouping the actions as they are is good.

> This is an example mock-up. But I think it's off-topic.

I think we'd need a different "Translate" icon that's more obvious if we made it a button. But also fits in that space. That icon unfortunately reminds me of all the times that someone used [FontAwesome](https://fontawesome.com/) but the font hadn't loaded! Also, would we show a letter in a box for Chinese/Japanese/Korean users? What about Thai and other scripts that are neither Latin nor Kanji based?

**Comment by philipzae** [comment]
> Because overloading the user with too many buttons at once, especially when their icons are unclear, also decreases the user experience.

Not sure how more than 3 buttons is considered overloading the user and the icons are self-explanatory and if not, they have tooltips, and once a user uses them them once, they know it forever. Just to clarify, I was only mentioning this for the timeline right-click button area, which has enough space to put 10 buttons per row.

> Maybe. But you're only going to be doing that from Tweet Info pages, which have a "Translate" link anyway. Or you're trying to handle the "someone used mixed text that didn't get picked up as needing translation and so I only want to translate part of it" use case, in which case a) most users would be selecting for other reasons and would see "Translate" for their own language and b) we don't have a source language so we're going to be using "auto" mode, which isn't as reliable. And c) we don't want to imply that we will let them translate to an arbitrary language (e.g. selecting native text and expecting to translate it to a foreign language).

Yes the scenario of mixed text or twitter didn't detect it was a translation. This happens to me everyday on tweetdeck.
a) not sure why this is a problem, as i right-click on selected text in firefox and i see many things in the context menu that I wouldn't use.
b) auto is reliable, as I use it everyday. If the translator isn't able to detect which language is being used, then its not a good translator.
c) translating to an arbitrary language, would happen if the user chooses on the translator website.

**Comment by tassoman** [comment]
> I think we'd need a different "Translate" icon that's more obvious if we made it a button. But also fits in that space. That icon unfortunately reminds me of all the times that someone used FontAwesome but the font hadn't loaded! Also, would we show a letter in a box for Chinese/Japanese/Korean users? What about Thai and other scripts that are neither Latin nor Kanji based?

I found that icon in utf8 support, provided by xfce emoji window. I also think doesnt fit perfectly. Common sense for translation/languages now is kanji+latin chars, as explained before in the thread

 text selection and contextual menu, for me it's something more. My early suggestion was for an auto discovery mode, most of times it works.
i'm also fine with "translate in default user language" but I would choose for a "favorite destination language", because translating from japanese to arabic for example, can be a mess. Most of us are fine with english as common intercultural language. That's because I mentioned "auto" in first instance

For the UX/UI trouble of messing things is very hard to say without user testing. Maybe a good choice is going for iterations, changing as little as possible

**Comment by IBBoard** [comment]
> the icons are self-explanatory and if not, they have tooltips

If you're relying on tooltips then your UX is bad. And it's not usable in all situations (e.g. touch screens)

> and once a user uses them them once, they know it forever

#298 😉

We've got the core functionality now. I'll close this now and we'll see how it goes in general use.

**Comment by philipzae** [comment]
> If you're relying on tooltips then your UX is bad. And it's not usable in all situations (e.g. touch screens)

You don't have to rely on it, but they are there for when there is confusion and also good for accessibility.

> #298 wink

When you use a non-standard icon and have no tooltip, definitely it can get confusing, especially when the icon next to it can be confused for it. In my case, I speak most of my time in tweetdeck and twitter.com for work and limited time in cawbird for my personal account. :smile:
