### ISSUE TITLE
Feed sorting options

### ISSUE THREAD

**Issue by visvital** [IBBoard/cawbird#162]
It would be great to utilize twitter capabilities for building the feed. Currently, the feed represents all twits based on the time they were published. What would be nice is to be able to see the feed similarly to how it is built for mobile/web apps made by twitter.

**Comment by visvital** [comment]
Yes, this was the suggestion. I believe, twitter uses some AI capabilities to organize the feed which (as they think) is the most suitable for the user.
They also expand the feed with the twits which were liked by the people you follow, etc. Sometimes it is rather handy.

Also, I didn't mean to substitute the chronological sorting with this one, but to add it as an option. If it is not available in the API, then I believe we can close this suggestion :)

**Comment by IBBoard** [comment]
The "home timeline" API is definitely ordered by time, and they don't give any information about how their algorithm might have ranked it for "top tweet" ordering.

Likes from people you follow will never be in the Cawbird timeline, because they shouldn't be in the timeline. If the people you followed wanted a tweet to be broadcast to the people who follow them then they'd use the RT button! Anything else is making assumptions about behaviour.
