### ISSUE TITLE
I have two accounts

### ISSUE THREAD

**Issue by jalalsfs** [IBBoard/cawbird#167]
Hello there!
I have two accounts on Twitter.
Is there a way to add another account to the app?

**Comment by IBBoard** [comment]
Click the avatar in the title bar then click "Add new account".

Because of the way Cawbird is currently designed then you can only have one account active at once. You'll need to click the avatar and swap between them when you want to check what has been posted. It's what I do between my IBBoard and CawbirdClient accounts - normally on IBBoard but occasionally check CawbirdClient.

**Comment by jalalsfs** [comment]
Okay, I got that, thank you.
