### ISSUE TITLE
Next button on last element of image gallery to cycle gallery

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#172]
When you get to the last entry of the popup image gallery, it doesn't have a next button on the right side of the image, but it would be nice to have it, so I can cycle back to the first image without closing the gallery and then having to open it up again.

A previous button on the first image gallery entry to cycle to the end of the gallery may also be beneficial to some.

**Comment by IBBoard** [comment]
I can see what you mean and it would be good to go back to the first image quickly without closing and reopening. But I think we need a better approach rather than cycling with the same buttons.

Twitter doesn't cycle. Eye of Gnome doesn't cycle. Feh does cycle but doesn't have buttons (it's just keyboard shortcuts).

Removing the "Next" button for the last one gives a clear indication that you're at the end (e.g. if it's a set of equal-sized images, and so it wasn't instantly obvious from the tweet display how many images there were, and you've clicked Next twice, is the next Next going to show the first image from a set of three or the fourth of a set of four?).

The only way it would work without confusing is if we had an "X of Y" overlay on the images. But I don't know how well that would work for accessibility.

**Comment by philipzae** [comment]
All these image viewers do - gThumb, Pix, Eye of Mate, ristretto. The gallery, like most of the app, is a mouse driven feature, so using keyboard navigation isn't the most intuitive option to solve this issue.

Maybe the next arrow can change into a cycle/refresh icon to when reaching the end. Maybe you can also have the right-click button as a means of cycling. Would be great to use the scrollwheel, but that is already used by the gallery. Maybe right-click plus scrollwheel could be an additional option for using the scrollwheel for cycling.

**Comment by philipzae** [comment]
Tweetdeck allows you to cycle through the gallery. https://twitter.com/reieyr/status/1283599219257864194

**First image of four**
![image](https://user-images.githubusercontent.com/4412114/87623408-60896580-c736-11ea-86d2-ee4dfe435bbc.png)
