### ISSUE TITLE
A couple of questions concerning cawbird behavior

### ISSUE THREAD

**Issue by morfikov** [IBBoard/cawbird#192]
I just installed cawbird on my Debian Sid (by building my own .deb package), and it looks the app works. 

The fist thing I noticed was the missing tray icon. I'm using an Xserver/Openbox setup without any DE. So three's no way to minimize/close the cawbird's window to tray, which makes it hard to say open all the time.

Sometimes it takes forever to load the twit list. The only way is to restart the app.

Also it looks like the dark theme isn't working -- nothing is changing when the "Use dark theme" button is switched.

It looks like when I play some video, there's no way to move its window or minimize it. When I click on the window, it disappears. It would be nice to move the window aside (and resize it), to be able to reach the cawbird main window and for instance scroll the twit list.

There's no way to pause the video, or to scroll its length. It also would be nice to have the two features.

--
cawbird 1.2.0
```
# cat /proc/version
Linux version 5.8.7-amd64 (morfik@morfikownia) (gcc (Debian 10.2.0-6) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35) #4 SMP PREEMPT Mon Sep 7 09:19:06 CEST 2020

**Comment by IBBoard** [comment]
> I just installed cawbird on my Debian Sid (by building my own .deb package), and it looks the app works.

We do have Debian Sid (Unstable) packages, but I'm glad you could build your own.

> The fist thing I noticed was the missing tray icon. I'm using an Xserver/Openbox setup without any DE. So three's no way to minimize/close the cawbird's window to tray, which makes it hard to say open all the time.

It's not missing, I just don't plan to implement it. See #45.

> Also it looks like the dark theme isn't working -- nothing is changing when the "Use dark theme" button is switched.

The dark theme switch relies on GTK themes having a "Dark" variant (like Adwaita). All we do is toggle a setting in GTK and let GTK do the rest. Every other report of dark theme not working has been something outside our control (e.g. theme without a dark variant, or Flatpak not honouring system themes and requiring extra downloads)

> It looks like when I play some video, there's no way to move its window or minimize it. … It would be nice to move the window aside (and resize it), to be able to reach the cawbird main window and for instance scroll the twit list.

No, you can't move it at the moment. #125 asked for resizing video. I can't see us ever implementing minimising or allowing you to keep the media while you go back to the timeline - it's just in the Cawbird UI approach. Either you're looking at the media, or you close it. We don't want to be keeping track of lots of open media.

> When I click on the window, it disappears.

Yeah, that's the way the original dev coded it and I've never changed it. It works fine for images, but I agree it's not great for video. But there have been other priorities and so it hasn't changed so far. It's also part of the reason why we probably won't do the "move the media and interact with the timeline", because then we either need to find a way to differentiate "click outside the media but on the timeline to keep the media going while you look at other tweets" from "click outside the media to close it" or we need to start adding title bars etc to the media and it stops being so streamlined.

> There's no way to pause the video, or to scroll its length. It also would be nice to have the two features.

Pausing and skipping is something I've had a vague plan for a while.  I think they're one feature of "media player controls for videos".

As there are multiple issues in one ticket here (and only one of them appears to be something we can do anything about and don't already have tickets for) then I'll close this and open a new ticket.
