### ISSUE TITLE
In RTL tweet, @ may be visually separated from rest of mention

### ISSUE THREAD

**Issue by lucaswerkmeister** [IBBoard/cawbird#194]
**Describe the bug**
[This tweet](https://twitter.com/ahval_ar/status/1305444972657770497) looks fine on the web (I cut off the “card” for the screenshot):
![Screenshot_2020-09-14 أحوال تركية on Twitter](https://user-images.githubusercontent.com/2346599/93085909-9abfa680-f696-11ea-9d19-35f382b1105b.png)
In Cawbird, the URL appears between the @ and the rest of the name:
![Screenshot from 2020-09-14 14-15-36](https://user-images.githubusercontent.com/2346599/93084730-cb064580-f694-11ea-9472-5d4c23592699.png)
In HTML terms, compare:
> ```html
> <div dir="rtl">حكومة #أردوغان تدمر مواقع التراث التركي @jwsal ahvalnews.com/ar/hkwmt-ardwg…</div>
> ```
> <div dir="rtl">حكومة #أردوغان تدمر مواقع التراث التركي @jwsal ahvalnews.com/ar/hkwmt-ardwg…</div>
with:
> ```html
> <div dir="rtl">حكومة #أردوغان تدمر مواقع التراث التركي &#x2068;@jwsal&#x2069; ahvalnews.com/ar/hkwmt-ardwg…</div>
> ```
> <div dir="rtl">حكومة #أردوغان تدمر مواقع التراث التركي &#x2068;@jwsal&#x2069; ahvalnews.com/ar/hkwmt-ardwg…</div>
(`<bdi>` or `<span style="unicode-bidi: isolate">` have roughly the same effect as U+2068 FIRST STRONG ISOLATE (FSI) and U+2069 POP DIRECTIONAL ISOLATE (PDI), but neither are allowed in GitHub Flavored Markdown. By the way, make sure you’re not viewing this bug report in WebKit/Safari, which [does not fully support dir isolation yet](https://w3c.github.io/i18n-tests/results/the-dir-attribute-isolation), see [bug #130823](https://bugs.webkit.org/show_bug.cgi?id=130823).)

I assume there’s a similar way to bidi-isolate the @mention in GTK (GLib? GNOME?).

**To Reproduce**

1. Search for ahval_ar’s account.
2. Scroll down until you find a tweet that ends in an @mention and then a URL.

Alternatively, search for the tweet mentioned above, or [this one](https://twitter.com/ahval_ar/status/1305420130042642434). (As in, paste the full URL into the search field.) Both have quote tweets that will show up in the search results.

**Expected behavior**
The @mention, as one logical component of the tweet, is visually in one piece.

**Screenshots**
See above.

**System details:**
 - OS: Arch Linux
 - Version: 1.2.0.2.r2.g0b9f96e6-1 (i. e. 0b9f96e6)
 - Package type: Arch Linux Git package

**Comment by IBBoard** [comment]
Gah. I thought I saw something like this once, but then didn't see it somewhere else (and it wasn't this bad, so I didn't know whether it was "correct" for rtl). Thanks for explaining all the BIDI stuff and what options are available.

It looks like their name does a similar thing on tweets in a list and shows `handle@ <arabic>`. That will be easier to fix, though, because I build that string whereas tweets are just parsed from data that Twitter supplies. I think I should be able to do something with the Unicode characters, though.

**Comment by IBBoard** [comment]
Okay, I think that fixes it, although I don't know what it'll do in the accessibility text for the "Retweeted by", and adding the Unicode BIDI characters would mean that every translation had to do it (unless I wrapped the username in case *it* is a different direction? But then the ASCII @-handle would be the bit that's in a different direction in the Arabic translation)

![Screenshot from 2020-09-14 19-42-30](https://user-images.githubusercontent.com/388582/93128416-5b5d7e00-f6c7-11ea-9b53-64566342f1b7.png)

(The hyphenation as the link wraps looks a bit odd, but I think that's unavoidable because you're reading the URL left-to-right and so you can't hyphenate at the start!)

Can you test Master?

**Comment by lucaswerkmeister** [comment]
Thanks, I think it’s working! A friend of mine pointed out that the Unicode control characters also carry over when you copy+paste the tweet text, but I’m not sure how else that could be fixed (whatever this HTML-like markup is, it doesn’t seem to support `<bdi>` tags, nor `unicode-bidi: isolate` styles), and I’m also not sure it’s even so wrong (arguably, those characters can also help ensure correct display when the text is pasted elsewhere, as long as the other place implements the Unicode bidi algorithm).

**Comment by IBBoard** [comment]
Yeah, I think it's "unavoidable (but potentially correct) behaviour" in this situation. Except for all of the superfluous ones we add in when it's all LTR text!

The Markup is HTML-like but is actually [Pango markup](https://developer.gnome.org/pygtk/stable/pango-markup-language.html). I've had issues with it not supporting seemingly sensible HTML things before for styling. But I guess they just implement the subset they need for convenience.

If it seems to work then I'll close it.
