### ISSUE TITLE
Use HdyAvatar

### ISSUE THREAD

**Issue by Kekun** [IBBoard/cawbird#199]
At GNOME we just created the Avatar Consistency initiative, which tries to make avatars look consistent across all GNOME apps by simply using `HdyAvatar`, see: https://gitlab.gnome.org/GNOME/Initiatives/-/issues/20

That would be great if Cawbird used it too! :)

**Comment by CodedOre** [comment]
I think there are three problems with using `HdyAvatar` in Cawbird.

First: How do we display an custom avatar using this widget? It seems like you can only add an icon from, and I don't think you can change the icon library on the fly.

Second: [How do we make the Avatar square?](https://github.com/IBBoard/cawbird/issues/56)

Third: What when we build against libhandy 0.0.13? When we already need an second system for this system, why not use this the whole time?

I think `HdyAvatar` is a great widget if your working within some parts, but for Cawbird i don't see a good use case.

**Comment by IBBoard** [comment]
Firstly, CodedOre is right with the second point - images are square. Square images let you make round avatars if you want (or any other shape). Round images do not let you make square a square avatar without it being tiny and having an odd border. Until it supports rectangular avatars then we won't use HdyAvatar.

On the displaying a custom avatar point, it looks like it *is* possible, but not made as clear as it could be in the docs. There's a ["set image load func" method](https://gnome.pages.gitlab.gnome.org/libhandy/HdyAvatar.html#hdy-avatar-set-image-load-func), but it says "A callback which is called **when the custom image need to be reloaded** for some reason". That doesn't make it clear that it's also the way to set the image in the first place.

It is explained a bit more clearly in the description, but it could be made more obvious. You'd then presumably pass in the pixbuf or Cairo surface or something as the user data (although that could be awkward for Twitter where you've got different scales of avatar as separate images). Most of the other functions and emphasis are on text or icon set images, which contributes to the lack of clarity.

Finally on the consistency, I don't know what features we'd gain by using HdyAvatar. Every Twitter user has an avatar, even if it is just a default one. The only time we don't show the avatar is when it fails to load. So, while the initials might be consistent there then we're never likely to see it much (and I'm not sure how well initialising a lot of Twitter handles would work!)

I think it's great that there's now a consistent way to do "avatar with fallback to initials (or icon) and auto-generated colour". I just don't agree with the trend of making them circular when so many images don't work in circles and it limits people's options.

Finally, thanks for putting Cawbird on the list of apps that Gnome thinks is worth including in a consistency initiative 🙂

**Comment by CodedOre** [comment]
Recently it came to my mind that, at least `AdwAvatar` becomes round by using css.

So, in a short experiment I could make it round using some custom css:

![square-example-one](https://user-images.githubusercontent.com/47981497/134165080-3f2087da-7607-4307-a1a9-d5a8ab7b46e5.png)
![square-example-two](https://user-images.githubusercontent.com/47981497/134165076-45361460-58ce-464c-b89c-684f0b80e98a.png)

We could use an css class when the avatar should be square, while using the upstream widget instead of an custom implementation.
Would like to hear your thoughts on that.

**Comment by CodedOre** [comment]
`AdwAvatar` now explicitly includes a [property](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/property.Avatar.custom-image.html), unlike (I guess) when we discussed it.

And it would make it more easier to implement avatars, as we only need to squarify it and leave drawing etc to a upstream widget.
So, I think we could just use that widget with a style class instead of porting the custom one for the rewrite.

Just less code for us to maintain.

**Comment by IBBoard** [comment]
It might work then. We'd just have to find a way to do [Verified/Protected icons](https://github.com/IBBoard/cawbird/blob/master/src/widgets/AvatarWidget.vala#L81-L119) (maybe with the [Overlay widget](https://docs.gtk.org/gtk3/class.Overlay.html)?) and find a different way to do the ["overlap" that's currently used in profiles](https://github.com/IBBoard/cawbird/blob/23e5c1758fa1548ee44a42ac0b9ae8c22f179174/src/widgets/AvatarWidget.vala#L189-L192).

So maybe we keep an "avatar" widget but it becomes a subclass of Overlay, has an AdwAvatar as the main child and Verified/Protected icons as overlaid children. We might then be able to do the offset on the Overlay as well rather than directly on the AdwAvatar.
