### ISSUE TITLE
Logging all tweeets into file

### ISSUE THREAD

**Issue by j1warren** [IBBoard/cawbird#2]
Hi, first of all, thanks for carrying the torch!

Since you're familiar with the code base, could you maybe give me a hint where to look in the sources to be able to log all tweets in the timeline?

**Comment by IBBoard** [comment]
All tweets and messages go through [stream_tweet](https://github.com/IBBoard/cawbird/blob/master/src/CbUserStream.c#L201) in `src/CbUserStream.c`. There's already a `#if DEBUG` block in there that prints messages to the console when built in debug mode. You should be able to do something from there.

If you just want a subset (e.g. log all mentions or log the timeline but not mentions by people you aren't following) then you could filter by type there, or you could the code in the relevant `…Timeline.vala`  file (e.g. `HomeTimeline.vala` or `MentionsTimeline.vala`)

Just be aware that the JSON can be quite large compared to the tweets!

**Comment by j1warren** [comment]
Thanks!
Ok, so if I want to log the Home timeline, I should hook the `private void add_tweet (Json.Node obj)`, right? How can I adjust its Json.Node obj to the code in stream_tweet which uses (JsonNode *node), so I can just copy-paste the code from DEBUG section you mentioned?

Also, does deleting `if`  for DELETE will make sure no tweets are deleted from Home timeline?

```
  public void stream_message_received (Cb.StreamMessageType type, Json.Node root) {
    if (type == Cb.StreamMessageType.TWEET) {
      add_tweet (root);
    } else if (type == Cb.StreamMessageType.TIMELINE_LOADED) {
      this.preload_is_complete = true;
    } else if (type == Cb.StreamMessageType.DELETE) {
      int64 id = root.get_object ().get_object_member ("delete")
                     .get_object_member ("status").get_int_member ("id");
      delete_tweet (id);
```
PS Why don't you advertise cawbird on a couple of forums, so people know about it?

**Comment by IBBoard** [comment]
> Ok, so if I want to log the Home timeline, I should hook the private void add_tweet (Json.Node obj), right?

If you add code in the `add_tweet` function in `HomeTimeline.vala` then it will be able to log every tweet in your timeline.

> How can I adjust its Json.Node obj to the code in stream_tweet which uses (JsonNode *node), so I can just copy-paste the code from DEBUG section you mentioned?

The debug block that I referenced is in C code and the home timeline is Vala. Vala is modern and object oriented and doesn't do C-like things with pointers using `*` (and, TBH, I don't know why Baedert wrote so much of this in C!).

Vala code makes C libraries available in a (slightly) more object-oriented way but with similar APIs. `json_generator_…` in C is available as [Json.Generator](https://valadoc.org/json-glib-1.0/Json.Generator.html) in Vala. So where C has:

```
  JsonGenerator *gen = json_generator_new ();
  json_generator_set_root (gen, node);
  json_generator_set_pretty (gen, TRUE);
  gchar *json_dump = json_generator_to_data (gen, NULL);
  g_print ("%s", json_dump);
```
the Vala is:
```
	Json.Generator generator = new Json.Generator ();
	generator.set_root (node);
	generator.pretty = true;
	string str = generator.to_data (null);
	print (str);
```
> Also, does deleting `if` for DELETE will make sure no tweets are deleted from Home timeline?

`Cb.StreamMessageType.DELETE` shouldn't happen any more. They were part of the streaming interface but now we just poll for new posts, so we don't see deletions (except when you delete your own post and Cawbird fakes a message - and I'm not sure that's 100% reliable).

> PS Why don't you advertise cawbird on a couple of forums, so people know about it?

Partly it's because I'm British and that kind of thing seems a bit bold and potentially spammy. Partly it's because I didn't want things to kick off too rapidly and it's easier if things grow more organically (but people are free to say that they're using the app!). Partly it's because I've not done much with Cawbird yet.

I have emailed the person who packaged Corebird for Arch. Not heard anything back yet, though.

**Comment by IBBoard** [comment]
I'm assuming this is done now.

**Comment by IBBoard** [comment]
The original advice still stands and the code should work if you make a custom build.

The  JSON can get quite large, though, especially for people following lots of accounts. Also, implementing this would open us up to "why don't you save the images as well" and then it gets far too easy for people to consume large amounts of disk space. So it's not going to be an official feature.
