### ISSUE TITLE
The bottom of quoted tweets is sometimes truncated

### ISSUE THREAD

**Issue by siebenmann** [IBBoard/cawbird#202]
**Describe the bug**
In Cawbird 1.2.1 (and I think from 1.2 onward), the bottom of some quoted tweets/retweets is truncated. I thought I had identified a pattern where this happens (where the quoted tweet was displayed in a single line), but since then I've found counter-examples.

It may be relevant that I'm seeing this on a HiDPI display.

**To Reproduce**
One tweet that this happens on for me is https://twitter.com/mjg59/status/1316213033757073408

**System details:**
 - OS: Fedora 31
 - Version: Cawbird 1.2.1
 - Package type: Fedora distro RPM

Here's a screen shot to show an example of it happening (on the above mentioned tweet, in my timeline, although it also happens when viewing mjg59's user details and timeline).

![cawbird](https://user-images.githubusercontent.com/865382/95941212-3c2d3b80-0dae-11eb-8e82-b84415a1224b.png)

**Comment by IBBoard** [comment]
Ugh, that's annoying. I suspect it is related to #57 (probably cec59433e2e135bf7a548e5a19a73270b24308f3). I thought I'd eventually got the calculations right , but seemingly there's something that I didn't account for.

Hopefully we just need to multiple some dimensions by pixel density to fix it.

**Comment by IBBoard** [comment]
I'm trying to work out how to debug this and I'm a bit stuck.

We don't actually override the size calculations (I never got them to be correct), so there's nothing to check in the calculations. And we only switch layout when we cross a specific width, so if you keep it the same size (or at least resize it  so that it's always bigger or always smaller than the limit) then it won't suddenly change where widgets are and be using a height based on incorrect widget sizes.

*But* I do see some widgets that aren't quite aligned correctly (looks like they're missing a bit of bottom margin) on my app occasionally, so clearly something isn't right with the height calculation.

I might be able to understand it a bit better if the underlying GTK code made any sense, but I couldn't find anything that did simple "add this height plus these margins plus...".

A few things to check:
* Is it only ever quoted tweets?
* Are there any patterns? Single-line tweets or double? All QTs or just some?
* Does it happen with RTed QTs?
* Does it still happen if you focus the tweet, or does it recalculate and resize?
* What about if you resize the window?

**Comment by siebenmann** [comment]
Some quick answers:
* it's not just quoted tweets; I've seen it on some retweets of plain tweets (cutting off much or all of who RT'd it at the bottom).
* It can happen with multi-line quoted tweets (or at least two lines), not just single line ones. It doesn't happen with all quoted tweets. Looking at the samples in my timeline, it may happen for all QTs where the new text is only one or two lines long, or maybe only one and a bit lines long. (For RTs, it is when the tweet's text is etc.) 
* it definitely happens for RTed QTs, where it will often cut off both the bottom part of the quoted tweet and the RTer.
* focusing the tweet appears to always not have anything cut off. It's hard to tell, because focusing a QT changes what's displayed (the QT turns into a link). If you go back to the main timeline display the tweet is still cut off.
* resizing the window can both eliminate and create these cut off tweets. Resizing to maximum width creates more of them; resizing to minimum eliminates most but not all.

**Comment by IBBoard** [comment]
What was I talking about. We *do* do the calculation 🙄

https://github.com/IBBoard/cawbird/commit/304b439a22b4548e59346fa24ed411b7d3dd639f

I suspect something still isn't right in there. And it is probably made worse by high-res.

**Comment by IBBoard** [comment]
Okay, I've had a brainwave. Can you test the `bug202-tweet-height-calculation` branch?

The brainwave is "don't calculate the height when we can safely let GTK do it"! It seems to be working for me so far. It *occasionally* glitches right on the "responsive" boundary, but that only happens while resizing and once you stop resizing then the next redraw event seems to fix it.

**Comment by siebenmann** [comment]
That branch appears to work right for me; I didn't spot anything cut off, including in situations where I'd have expected it (and where the current version does cut things off, based on some spot checks).

**Comment by IBBoard** [comment]
That's good 🙂

Is it okay *while* you resize and cross the responsive limit? (440px normally) I'm not worried about the occasional glitch right on the threshold that then fixes itself as you move more, but does it normally look okay while actively resizing?

**Comment by siebenmann** [comment]
It looks normal to me. I don't see any visual anomalies, and cross-comparing the branch against the normal version they booth seem to act the same. (I don't normally resize my cawbird windows so I don't have much experience in how it should look.)

**Comment by IBBoard** [comment]
"Responsive" mode moves the text and image under the avatar ([announcement](https://twitter.com/CawbirdClient/status/1301466790237745157)).

Sometimes, when I resize across that threshold I get the "cropping" problem you first described here, but I assumed it was due to a slight mismatch in width-for-calculation vs width-for-layout caused by scroll bars or something. What I can briefly get is this:

![Screenshot from 2020-10-19 20-29-10](https://user-images.githubusercontent.com/388582/96503012-89942780-124a-11eb-92cf-6b497da37dc5.png)

But it is tricky to recreate, and within a couple of seconds of letting go then it seems to recalculate and fix it.

If it doesn't go obviously wrong (or only does it briefly, as it does for me) then all is good.

**Comment by siebenmann** [comment]
I didn't see any of those anomalies even while I was resizing small, and certainly not afterward (when I stopped and let it stabilize).
