### ISSUE TITLE
Feature Request: AppImage

### ISSUE THREAD

**Issue by danrobi11** [IBBoard/cawbird#203]
Hello. Thank you for Cawbird. About AppImage support?

**Comment by IBBoard** [comment]
The Flatpak is semi-official - someone else built it and maintains it and I try to remember to increase version numbers when we do a release.

If the community builds AppImage then we'll link to it (the same as the Snap) but we won't build or maintain it.

Personally, I'm a pure-native person. Despite what people say, all I see with the alternate formats is [drawbacks](https://github.com/IBBoard/cawbird/issues/134), [package](https://github.com/IBBoard/cawbird/issues/73) [specific](https://github.com/IBBoard/cawbird/issues/68) [bugs](https://twitter.com/scearley/status/1314735683253096448) and [additional maintenance headache](https://github.com/flathub/uk.co.ibboard.cawbird/pull/1/files). The only reason I made the Flatpak semi-official is because it is Gnome's preferred format.
