### ISSUE TITLE
Cawbird segmentation fault on startup

### ISSUE THREAD

**Issue by nedludd** [IBBoard/cawbird#213]
Looks like [this commit](https://github.com/IBBoard/cawbird/commit/fcbdf60c37c3361b613b5a8351e0d476c712560e) causes Cawbird to segfault on startup.  Here is what it looks like: https://pastebin.com/nfuCgD0i

I reverted to the previous commit and it started up correctly.

Unfortunately I don't have the skills to debug it myself, but perhaps someone could take a look.

**System details:**
 - OS: Arch Linux (up to date)
 - Package type: git build

**Additional context**
Found this issue when running the 'cawbird-git' package from the Arch AUR

Running `G_MESSAGES_DEBUG=cawbird cawbird` gave no useful debug output.

**Comment by IBBoard** [comment]
Does 8ea2bb20e0f46ea49e1d46136d8c9314c5083fdb fix it? @fbellet already reported an issue with the commit you mention (because I didn't really know what I'm doing with X Init stuff) and gave a fix that worked for them.

**Comment by nedludd** [comment]
Seems like it doesn't.  Just built with that specific commit and it segfaults.

**Comment by IBBoard** [comment]
Awesome. So without that then it crashes for some people when they play videos. With it you get a segfault. And I can't recreate either because I don't get segfaults on videos or at start up.

I guess we need a bit more info:
* Display server (X or Wayland)
* Desktop environment
* Graphics hardware and drivers
* Some other things that I can't think of right now.

**Comment by busybox11** [comment]
Hey,

I just discovered this and tried installing cawbird using the AUR. As you may have guessed, I also have a segfault.

I'm using X on i3-gaps (compton-tryone), have an AMD A9-9425 and its integrated Radeon R5 GPU (can't find the model).

I compiled it using the `cawbird` AUR package.

**Comment by nedludd** [comment]
* Display server: X (xorg-server 1.20.9-3)
* Desktop environment: awesome wm (although it does the same under Gnome and Plasma
* Graphics hardware: NVIDIA GeForce GT 710
* Graphics drivers: nouveau 1.0.16
* Kernel: 5.9.8-zen1-1-zen

**Comment by fbellet** [comment]
It would be interesting to rebuild with CFLAGS='-g', launch cawbird under gdb, put a breakpoint in XInitThreads, run it and verify if XInitThreads() is reached before the segfault.

**Comment by IBBoard** [comment]
Looking at the core dump, it's in `g_application_run` at frame 17, so doesn't that mean that it got to `cawbird.run (args)`?

On the specs, the common feature seems to be Arch. It's not specific to a DE, it's affecting NVidia and Radeon graphics.

Having a Google around, it's possible that we're still not doing the init right (even though it fixed @fbellet's problems). [This thread](https://www.reddit.com/r/rust/comments/84k3y2/getting_a_segfault_in_pthread_mutex_lock_with/dvsbs3r/?context=3) on Reddit says about doing GDK inside the GTK init thread. But we're calling GDK functions before we've got to any GTK stuff (because apparently that's the order we need to keep GStreamer working)

**Comment by IBBoard** [comment]
It would be good to get this tested, understood and fixed so that it's not a blocker on a next release. Otherwise I'll have to undo the patches for #123.

**Comment by fbellet** [comment]
Why not calling XInitThreads() unconditionnally ? Since the app is linked against libX11 anyway, it probably doesn't hurt to initialize its locking infrastructure, even when using wayland. Then we could avoid calling gdk_init().

**Comment by IBBoard** [comment]
But what happens if you XInitThreads() while someone is running Wayland? The whole point of the if statement is to do the right thing for the current environment and not just run all code regardless.

**Comment by IBBoard** [comment]
I've added a branch so that we can put some debugging in without adding noise in Master.

@fbellet and @nedludd - What logging do you get if you build that branch and run `G_MESSAGES_DEBUG=cawbird build/cawbird | grep DEBUG`?

(We need the `G_MESSAGES_DEBUG` to enable debugging before an `#if DEBUG` call kicks in later, and we need `grep DEBUG` to remove all of the JSON noise that may otherwise swamp the terminal)

**Comment by fbellet** [comment]
Running Fedora 32, with GNOME on Xorg:

```
[bellet@vm1 x86_64-redhat-linux-gnu]$  G_MESSAGES_DEBUG=cawbird ./cawbird
(cawbird:3636): cawbird-DEBUG: 22:16:59.898: Built with X11 support
(cawbird:3636): cawbird-DEBUG: 22:16:59.898: Initialised X threads with status 1
(cawbird:3636): cawbird-DEBUG: 22:17:00.017: Cawbird.vala:267: startup
[...]
```

and with GNOME on Wayland:

```
[bellet@vm1 x86_64-redhat-linux-gnu]$  G_MESSAGES_DEBUG=cawbird ./cawbird
(cawbird:5165): cawbird-DEBUG: 22:21:33.834: Built with X11 support
(cawbird:5165): cawbird-DEBUG: 22:21:33.930: Cawbird.vala:267: startup
[...]
```

**Comment by fbellet** [comment]
> But what happens if you XInitThreads() while someone is running Wayland? The whole point of the if statement is to do the right thing for the current environment and not just run all code regardless.

Forcing XInitThreads() to be called with GNOME on Wayland doesn't break anything (in my case).

I think calling XInitThreads() should be safe, since it just initializes helper functions and create some mutexes (in Wayland too it should not have bad side effects, as applications running with wayland won't use the X protocol anyway, so it just initializes things that won't be used):

https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/master/src/locking.c#L588

**Comment by nedludd** [comment]
I get nothing: 

`~/tmp/cawbird 
$ G_MESSAGES_DEBUG=cawbird build/cawbird`
`[1]    31563 segmentation fault (core dumped)  G_MESSAGES_DEBUG=cawbird build/cawbird`

**Comment by IBBoard** [comment]
That's… odd. That suggests `GDK_WINDOWING_X11` is false/unset. Which suggests that `$enable_x11_backend` wasn't set in [the GTK build](https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.18/configure.ac#L380-389). But you're running XOrg server.

Do you know [which backends it was built with](https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.18/configure.ac#L325-344)?

**Comment by fbellet** [comment]
I could reproduce the segfault, using plasma + xorg on arch linux. This is caused by gdk_init being called before XInitThreads. Calling XInitThreads() unconditionnally works in that case too. Calling XInitThreads() before gdk_init() works too. The crash is specific to plasma + xorg.

**Comment by IBBoard** [comment]
I guess that makes sense. But at the same time, it's odd. There's no way to check that you're on an X11 platform without invoking GDK, which needs you to have initialised X properly! 

Also, what if the package is build on an X11 enabled platform (so the IFDEF is true and it compiles in the call) but it is run by someone on a pure Wayland system (so they don't have any X11 packages installed and presumably don't have XInitThreads)?

**Comment by fbellet** [comment]
> I guess that makes sense. But at the same time, it's odd. There's no way to check that you're on an X11 platform without invoking GDK, which needs you to have initialised X properly!
> 
> Also, what if the package is build on an X11 enabled platform (so the IFDEF is true and it compiles in the call) but it is run by someone on a pure Wayland system (so they don't have any X11 packages installed and presumably don't have XInitThreads)?

When the package is built on a platform with X11, and having the X11 backend in gdk, the shipped binary will be linked against libX11, and this dependency will have to be resolved on users's side, by installing libX11, even if libX11  is solely used by XInitThreads(). A packager probably wants to ship an application with many options enabled, so it is as feature-full as possible. The drawback is that the user of such package has to install libraries, that he may not need on his system.

**Comment by IBBoard** [comment]
Forcing libX11 on Wayland people just because the build server was configured to use it seems a bit not good. Which is what's bothering me.

But, thinking about it, I guess that if you did build it with X11 enabled and not have the libraries installed (because you're pure Wayland) then you've got a dangling reference to a function/symbol that doesn't exist, and that's not great either. Although it should never crash because either the "if display is X11" statement will be false and you'll never get to the X11 call under Wayland or the "if display is x11" is true and so you must have libX11.

Your only option to avoid trailing/unnecessary dependencies would be to have separate `cawbird-wayland` and `cawbird-x11` packages.

**Comment by IBBoard** [comment]
Okay @nedludd and @busybox11, does that latest update to the branch fix it for you?

**Comment by busybox11** [comment]
Apparently it does, yeah.

**Comment by IBBoard** [comment]
Okay. I don't particularly like it and it feels like I'm doing something wrong, but if everyone is reporting that there are no crashes with it that way and crashes without it or with the display check then I guess that's what we'll go with!

**Comment by IBBoard** [comment]
I'm looking in to #246 and trying to work out how the command-line parsing etc should work. I've tripped over [this thread](https://discourse.gnome.org/t/what-command-line-arguments-does-gtk-init-filter-out/3140/2) on the Gnome Discourse that says "Don't use the old init functions".

Now, it is talking GTK, whereas we're doing XInit and GStreamer, but it makes me wonder whether we're doing it wrong anyway. I'm looking around to see if there's a "correct" way to fix this.

**Comment by IBBoard** [comment]
@nedludd @busybox11 @fbellet Can someone check the newer (pure Vala) version of the fix and make sure it still works? Thanks.

**Comment by fbellet** [comment]
It works for me! This pure vala version is cleaner, good work, thanks!

**Comment by IBBoard** [comment]
That's good, thanks 🙂

**Comment by nedludd** [comment]
I hate to be the bearer of bad news, but I think there are still issues.  My system has been having hard lockups for some time (screen frozen, mouse and keyboard frozen, only solution is to reboot)

I wasn't sure what it was until I noticed that it only happened when Cawbird was running.  In fact it happened when I started Cawbird with the new pure vala version for the first time.

I've done some experimenting and it does seem to happen only when Cawbird is running.   Unfortunately there are no logs or output since the system is locked completely.

**Comment by IBBoard** [comment]
That's… less than helpful of the OS!

When it locks, does the numlock key still work, or the Alt+SysRq commands? Just wondering whether it's X or a full kernel lockup (which would be impressive from a Twitter app!).

What we have now appears to be The Correct Way™ for initialising GTK and GStreamer, though, and we shouldn't hit GStreamer code until you open a window, so I don't know what could be causing it.

**Comment by nedludd** [comment]
Let me see if I can reproduce.  Sometimes it takes a while.

**Comment by nedludd** [comment]
Yeah, it's a hard lock.  No NumLock, nothing.  Ran without Cawbird for 24 hours, no lockup.  Ran Cawbird for a couple of hours and it locked.

Like I said, it's only circumstantial, but it does seem to be related.
