### ISSUE TITLE
Remove Emoji button?

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#243]
While working on the extended DM functionality, I've started questioning whether we need the emoji button.

If you right-click and go to Insert Emoji then you get an identical emoji picker in a popover. And if you press `Ctrl+Shift+E` then you can do a search by name. ([More description and options on StackOverflow](https://askubuntu.com/a/1045916/19817))

So, do we really need the emoji button when the OS has built-in ways to do it (and distros that don't have "Insert Emoji" built-in probably don't have the required emoji data files anyway)?

[![](https://api.gh-polls.com/poll/01ESEE6SDT34MBBKZHMQZD0KA1/Yes%2C%20keep%20it%20because%E2%80%A6)](https://api.gh-polls.com/poll/01ESEE6SDT34MBBKZHMQZD0KA1/Yes%2C%20keep%20it%20because%E2%80%A6/vote)
[![](https://api.gh-polls.com/poll/01ESEE6SDT34MBBKZHMQZD0KA1/No%2C%20Insert%20Emoji%20and%20Ctrl%2BShift%2BE%20is%20enough)](https://api.gh-polls.com/poll/01ESEE6SDT34MBBKZHMQZD0KA1/No%2C%20Insert%20Emoji%20and%20Ctrl%2BShift%2BE%20is%20enough/vote)

If you vote "Yes, because…", please don't forget to say what the reason is 😉

**Comment by IBBoard** [comment]
/polls "Yes, keep it because…" "No, Insert Emoji/Ctrl+Shift+E is enough"

**Comment by IBBoard** [comment]
/polls "Yes, keep it because…" "No, Insert Emoji and Ctrl+Shift+E is enough"

**Comment by IBBoard** [comment]
/polls "Yes, keep it because..." "No, Insert Emoji and Ctrl+Shift+E is enough"

**Comment by IBBoard** [comment]
One of my big annoyances at the moment is that the symbols for the tabs in our viewer are a mix of Noto Colour Emoji and Symbola, whereas Insert Emoji is all Symbola.

Also, it breaks when GTK updates its emoji data (#148)

**Comment by CodedOre** [comment]
I would say yes, because these options are not commonly know and you have no graphical way to

**Comment by CodedOre** [comment]
I personally use rarely emojis, but I would still argue for keeping the button, because I suspect "right-click to insert" or the shortcut are not that widely known (first time I heard about them), and I think there are some people who wants the fast access to it.

However, as soon as you use an virtual keyboard (on Gnome and on Phosh for example), you get an easy selection from them, which makes it there obsolete (which is the reason I includes the emoji button only on the desktop example in my mock-up), and I can understand that it makes sense to remove it. 

At the end, I probably still rather wait for other with more emoji usage to answer this question...

**Comment by IBBoard** [comment]
> because I suspect "right-click to insert" or the shortcut are not that widely known (first time I heard about them), and I think there are some people who wants the fast access to it.

GtkEntry has an ["Emoji" option](https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry--show-emoji-icon) that puts a clickable icon at the end, but there doesn't appear to be an equivalent for multi-line text boxes.

Right-click to insert isn't _that_ hidden. And if we're the only app with a dedicated "Emoji" button then surely people are using it in other places anyway? Or do people think that we're the only GTK app that supports emoji insertion because we're the only one with a dedicated button?

I think it made more sense in the early days of Corebird when Baedert was (presumably) doing it because easy access didn't exist and wasn't prevalent. But does it make sense now that emoji are EVERYWHERE?

**Comment by schmittlauch** [comment]
> Right-click to insert isn't that hidden.

Where shall people learn of it then? Do you expect them to discover it by accident when doing a right click for other reasons?
Adding a hint for that on first launch could help.

> And if we're the only app with a dedicated "Emoji" button then surely people are using it in other places anyway?

I'm using Dino as well, and they also have a dedicated Emoji button.

> Or do people think that we're the only GTK app that supports emoji insertion because we're the only one with a dedicated button?

While I'm mostly a KDE Plasma user yes, I didn't know about the general Gtk Emoji input. I rarely use the right click context menu because I do copy-pasting via keyboard shortcuts, so no need to open the context menu.

**Comment by IBBoard** [comment]
> Where shall people learn of it then? Do you expect them to discover it by accident when doing a right click for other reasons?
> Adding a hint for that on first launch could help.

I don't know. Ask the GTK folks. It's their menu item!

I admit it's not great, but duplicating UI seems like a bad idea.

**Comment by IBBoard** [comment]
Closing this now.

"No, we don't need it" would have won because while "Yes, we need it because…" had more votes, there wasn't much of a "because". While I understand that people might not realise that emoji can be inserted in any GTK app, we can't expect all apps to have an emoji button. Even Windows 10 has a shortcut for emoji these days.

But the catastrophic limitations of the default emoji popover and the lack of ability to move to GTK4 (where it is apparently fixed) means that we're stuck with the buttons because of our not-full-screen windows.
