### ISSUE TITLE
Missing edit profile icon on Pinephone

### ISSUE THREAD

**Issue by justinesmithies** [IBBoard/cawbird#259]
**Describe the bug**
When using Cawbird on the Pinephone with Arch the user profile menu is off screen to the right which clips the edit profile icon.

**To Reproduce**
1. Click on user profile image.
2. pop up window off screen on the right

**Expected behavior**
To be able to see the whole of the pop up window on the pinephone.

**Screenshots**

**System details:**
 - OS: Arch Arm
 - Version: latest
 - Package type: cawbird-git from the Arch AUR repo

**Additional context**

Running `G_MESSAGES_DEBUG=cawbird cawbird` can give useful debug output.

**Comment by IBBoard** [comment]
Example: https://twitter.com/JustineSmithies/status/1344738566686044161

**Comment by IBBoard** [comment]
Just doing a quick investigation and test and… I think there might be limited amounts that we can do with this because of various problems inherent in GTK "popovers".

If I put a really long name in then it gets quite wide:

![Screenshot from 2021-01-01 19-21-00](https://user-images.githubusercontent.com/388582/103444984-b01d0880-4c66-11eb-90fc-0bc4ca6685be.png)

And if I shrink the window then the popover doesn't shrink (and because of an [old, known GTK issue that they never fixed](https://gitlab.gnome.org/GNOME/gtk/-/issues/3307#note_990189), that cropping will stay in X):

![Screenshot from 2021-01-01 19-22-13](https://user-images.githubusercontent.com/388582/103444982-af847200-4c66-11eb-8245-decd5e00da53.png)

There might still be *some* way to work around it other than reducing margins, but we'll have to see.

**Comment by IBBoard** [comment]
I've put in some tweaks, but it may not fix it. Are you able to build a new version from "master" and test?

I've also tried size requests on the popover (whether when showing the popover or when the window gets a size allocation) and it doesn't seem to honour those, so we don't appear to be able to say "no bigger than the window".

I also tried setting `Gtk.PopoverConstraint.WINDOW` which should "Constrain the popover to the boundaries of the window that it is attached to" and… it doesn't. It still overflows and gets cropped.

https://valadoc.org/gtk+-3.0/Gtk.PopoverConstraint.html

**Comment by IBBoard** [comment]
Okay, it's not perfect, but hopefully that latest commit makes things a bit more workable.

We've also now got a more sane default value for maximum name lengths before truncating, because 40 characters is huge!

**Comment by ahoneybun** [comment]
Let me see if I can build it from master or is this from the latest release?

**Comment by ahoneybun** [comment]
I built it on the PinePhone on Arch though it seems that it can't use Firefox to get me the key to log in so I need to get around that.

**Comment by IBBoard** [comment]
I've seen comments on Twitter that v1.3 is pretty much as good as it'll get on PinePhone/Phosh (without the libhandy redesign) so I'll close this.
