### ISSUE TITLE
Replies aren't getting loaded

### ISSUE THREAD

**Issue by uralets** [IBBoard/cawbird#285]
Hello!

I've been using (well, trying to at least) Cawbird for quite some time now and one of the more serious issues I've encountered is that all the time I use it (over several 1.* version changes) the replies to the tweets load either only partially or won't load at all.

Is it a known issue or is it just me hitting this? It was always like this since I've first fired up Cawbird, back at least to the times when the replies feed loaded on top of the tweet for some reason. And has been everpresent.

**Describe the bug**
When entering almost any tweet, the replies are loaded only partially or there are no replies loaded at all

**To Reproduce**
1. Enter a tweet
2. Try to scroll down to see the replies
3. See only a handful (while there's actually much more) or no at all
4. Nothing I can think of doing seems to prod the loading of replies

**Expected behavior**
See the replies feed in full, loaded as needed on scrolling down.

**Screenshots**
![cb](https://user-images.githubusercontent.com/45916341/104838661-4e9f9f80-58de-11eb-8ef5-65355731c4fb.png)
![web](https://user-images.githubusercontent.com/45916341/104838677-5b23f800-58de-11eb-9355-b3213d1406bb.png)

**System details:**
 - OS: Ubuntu MATE 20.04
 - Version: 1.3.2-1+4.1 (any one I've used actually)
 - Package type: Official: http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_20.04/ 

**Additional context**
Another example: This https://twitter.com/mich261213/status/1350548859752222722 has TONS of replies. At the time of writing, Cawbird would load only a couple dozen, judging by the timestamps the latest ones (couple a minutes old).
*Sometimes* it does work correctly I think, as far as I can tell this happens mostly when there's only a handful/couple a dozen of replies max.

`G_MESSAGES_DEBUG=cawbird cawbird` doesn't give anything useful, in fact there's no output at all after the initial spew of cawbird-DEBUG messages

**Comment by IBBoard** [comment]
Looking at how many mentions mich261213 gets and how many I assume the NY Rangers get, I think this is almost certainly a ["Twitter says no" problem](https://github.com/IBBoard/cawbird#limitations).

Using the older v1 API, there is no way to fetch replies to a thread. So we approximate it by doing two searches - one is "to:@-author -from:@-author" (i.e. all tweets to the author but not by the author) and the other is "to:@-author from:@author" (i.e. the self-replies) and then we check which ones are actually replies to this message and build the thread from there. If there are too many mentions that aren't part of the thread then it fails to build a thread, but it's the best that we can do. 

If someone posted one tweet and had 200 replies and no-one ever mentioned them outside that thread then we'd load all 200 tweets. If it's someone like a celebrity or a major sports account that's going to get *lots* of mentions then the results become worse the more popular they are.

It looks like request logging only happens in debug builds, though (probably because it takes time to rebuild the URL from the request).

The new Twitter API will support searching by conversation ID, which lets you search for messages just from a specific thread. But the new API also changes the structure of the tweet data, so we've not implemented it yet.

**Comment by uralets** [comment]
Thanks for a quick and informative answer!
That would explain why it sort of works for me sometimes.

The stuff you have to do to simply fetch the replies... Damn those proprietary APIs :((
With limitations like that, it's a long shot for any sane desktop client to become feature complete and really usable.

Thanks again, closing.

**Comment by IBBoard** [comment]
The conversation ID will definitely be a big improvement for this use case. But it's also reasonably clear that Twitter only tolerate third-party clients rather than actively supporting them. Their real use case for the API is for big companies to pay them lots of money so that they can do "customer service" stuff by searching for mentions of their company etc.
