### ISSUE TITLE
Add spacing between images

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#290]
Its hard to tell the number of photos that are in a tweet, when they are all next to each other and no spacing is between them. Ideally 2 pixels of spacing would be good, but even 1 would be helpful.

[Is this 1 or 4 images](https://twitter.com/emirates/status/1351088019911147520)? 4  
![image](https://user-images.githubusercontent.com/4412114/104967357-97e61100-59fc-11eb-8a7d-d91877828671.png)

[Is this 1 or 2 images](https://twitter.com/popey/status/1351186003218870272)? 1  
![image](https://user-images.githubusercontent.com/4412114/104967389-ac2a0e00-59fc-11eb-8ad0-69a51d8d12c2.png)

**Comment by IBBoard** [comment]
I know what you mean. I've probably hit it a few times before but never thought about doing much with it, because it's normally reasonably obvious (those four images change a lot and aren't likely to be one huge panorama shot) and hovering changes one image.

But it's a single line fix, so it's done.

**Comment by philipzae** [comment]
Thanks.
