### ISSUE TITLE
Notifications repeatedly notify for the same tweet

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#292]
I set 'On New Tweets' to 'Every' or 'Stack 5' and i repeatedly get a notification about the same tweet(s) after a few minutes.

From my notification log file
![image](https://user-images.githubusercontent.com/4412114/105197776-68e3b280-5b56-11eb-8cee-96b1b3c77674.png)

**Comment by IBBoard** [comment]
Ah, that's probably something to do with the fix for #147 where we overlap our requests to try and reduce the chance of missing tweets due to eventual consistency.

I'll have to look at how we handle notifications.

**Comment by philipzae** [comment]
Just to be clear, it wasn't limited to just the same tweet, as I would set it to 'Stack 5' and that notification would also popup multiple times.

**Comment by IBBoard** [comment]
I tested with "Every" (since I don't get 5 tweets every 2 minutes - which is our polling time) and it didn't come back after the patch. But the behaviour before the patch and examining the code was definitely caused by it notifying when the same tweet came in due to overlapping requests, even though you had seen that tweet before.

If it's still happening after the patch then it would help if there are any patterns that you can see (Always the same tweet, even after you read some? Always the latest tweet when nothing new appears but changes when a new tweet comes in? Numbers don't match what Cawbird is reporting?)

**Comment by philipzae** [comment]
I didn't have over 5 tweets with 2 minutes either, but the 5 tweets notification still kept popping up for the maybe 1 tweet which was there. :smile:

![image](https://user-images.githubusercontent.com/4412114/105408486-75e0ce80-5c48-11eb-9639-3789329bb85b.png)

The only thing that I could say is that I wasn't at the top of the timeline and don't have 'auto scroll on new tweets' enabled.

**Comment by IBBoard** [comment]
If you had a multiple of five tweets unread and then each poll returned overlapping tweets but no new tweets then the old code would have kept notifying every two minutes. The moment a new unread tweet came in then it would have had 5n+1 tweets and so the "is divisible by zero" check wouldn't have passed and it wouldn't notify until you were at 5n+5.

But now we shouldn't even get that far because the overlapping tweet is marked as "not a new unread tweet" and so it returns before it notifies.

**Comment by philipzae** [comment]
Tried to test the patch to see if it works for all scenarios by building master, but got this error.
![image](https://user-images.githubusercontent.com/4412114/105551597-4b604580-5d1c-11eb-954e-590acdc5a80c.png)

**Comment by IBBoard** [comment]
That's because the settings schema was updated recently, but your installed schema doesn't include the new fields. Try the ["GSettings in memory" command from the README](https://github.com/IBBoard/cawbird#compiling).

**Comment by philipzae** [comment]
Doubt this will work for me as I build cawbird in a VM and copy the executable to my host OS.

**Comment by IBBoard** [comment]
It should work if you copy the `build/data/` directory and set the paths correctly. You'll need to copy and install the schema at some point. Unless you're planning to always install the latest Cawbird package and piggy-back all of its libraries and config to make the custom executable work.

**Comment by Asday** [comment]
When will this fix make it to a release?  I am a stupid stupid idiot and only know how to let Manjaro take care of things for me, so my guess is that 1.3.3 needs to exist for me to receive this fix.

**Comment by IBBoard** [comment]
Soon-ish. I've had some other priorities and there have been a few things that were found, fixed and getting a bit of testing that delayed my earlier release plans.

**Comment by Asday** [comment]
Aight beast, thanks for both the quick reply and for dealing with my pestilent presence.  I'm excited for the release.
