### ISSUE TITLE
Reduce size of information icons

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#294]
I would recommend reducing the size of the info icons from 32px to 24px, as they seem way to large.
![image](https://user-images.githubusercontent.com/4412114/105200061-dc86bf00-5b58-11eb-875f-36f3662b3f9d.png)

**Comment by IBBoard** [comment]
It's slightly less intrusive with the Tango icon theme, which uses a lightbulb.
![screenshot](https://user-images.githubusercontent.com/388582/105220790-1d2e0a80-5b50-11eb-94e2-7cc6ea8d9066.png)
But you're right, 24px probably isn't too small.
![screenshot](https://user-images.githubusercontent.com/388582/105220832-2e771700-5b50-11eb-9505-9167577de2f9.png)

**Comment by philipzae** [comment]
Would be good to keep the icon at the bottom of the image as well, as many of the bulbs aren't touching the image. If that is difficult, then possibly the top left or top right corner.

**Comment by IBBoard** [comment]
You mean like e7cfd69, which I did about an hour ago, just after the size fix? 😁

**Comment by philipzae** [comment]
On my other PC which shows the bulb, I think it is problematic to leave it up to the theme to decide what icon to show.
![image](https://user-images.githubusercontent.com/4412114/105232614-1324ff80-5b82-11eb-8b0b-f2e1e0774b03.png)

**Comment by philipzae** [comment]
> You mean like [e7cfd69](https://github.com/IBBoard/cawbird/commit/e7cfd69d539ef5ca0d7da78a5d2ad3071760229f), which I did about an hour ago, just after the size fix? grin

:grin:

**Comment by philipzae** [comment]
Another one that i barely even new had it
![image](https://user-images.githubusercontent.com/4412114/105232905-87f83980-5b82-11eb-9c9d-ea86124e58d3.png)

**Comment by IBBoard** [comment]
Yeah, I saw one recently that was less obvious because of the content in the image. But I feel like we should be using the system theme's icon here because it's consistent for the user. And even the blue circle with an "i" won't be entirely obvious on some (blue) backgrounds.

I would try to put a "glow" around it, like I did recently with the upload progress icons, but I don't think there's an obvious/reliable way to do that when you've got an icon instead of an SVG component with a border.

**Comment by philipzae** [comment]
> Yeah, I saw one recently that was less obvious because of the content in the image. But I feel like we should be using the system theme's icon here because it's consistent for the user. And even the blue circle with an "i" won't be entirely obvious on some (blue) backgrounds.

Is the penguin icon using the system theme? This definitely has to be an icon provided by penguin and not left to the theme, especially as there is no setting in cawbird to change which icon theme should be used in the cawbird interface. But whatever icon that would be used needed to be able to work on any possible background, maybe by having a black stroke around it.

**Comment by IBBoard** [comment]
The penguin for the emoji is whatever your system font provides, because it's text on a button. My system gets it from Noto Color Emoji.

I guess the "work on any possible background" requirement might be a good enough reason to break from system themes. I try not to and I intentionally stripped back Cawbird's custom themeing a while back (hence the loss of the black action bar, because it's fine in Ubuntu but not right for stock Adwaita), but there's always exceptions to every rule.
