### ISSUE TITLE
Adjust font size setting

### ISSUE THREAD

**Issue by volt4ire** [IBBoard/cawbird#33]
Would you consider adding the ability to adjust the default font size for Tweets' text? Thanks!

**Comment by IBBoard** [comment]
It's probably possible, but it's low priority for me.

Cawbird doesn't do anything special with the font size, so it should just be using your system's "interface" font size.

Is there a specific use case where using the system interface font size isn't appropriate?

**Comment by volt4ire** [comment]
Thanks for considering this! I use Cawbird on a 2-in-1 laptop, so I often adjust apps' font sizes based on whether I'm using it in touch mode or with second monitor. If I were to adjust the native system interface font setting for GTK apps so that Cawbird's text appeared the appropriate size, it would cause my other GTK apps' fonts to be too large.

**Comment by starvald** [comment]
same issue when i tried corebird, you can try this. change number to suit your display.
env GDK_SCALE=1.3 GDK_DPI_SCALE=1.3 CLUTTER_SCALE=1.3 cawbird

**Comment by volt4ire** [comment]
@starvald thanks so much that's a good solution for now!

**Comment by shamim2018** [comment]
I want this feature too! Can't change system font settings in Elementary OS Juno. So adjust the default font size for Tweets' text is very much essential to me. Fonts for Indic scripts are the main problem here.

**Comment by chriztheanvill** [comment]
Please, could you make this feature. My fonts are tiny.

**Comment by IBBoard** [comment]
What platform are you on? And what is your default font size? It would also help if you could show what "tiny" looks like.

I still don't understand how most fonts can be fine for people in other apps but too small in Cawbird. We don't do anything special with fonts. We honour the system font size.

**Comment by chriztheanvill** [comment]
Fedora 33 kde 5.20.3
Sans Serif
General 10pt
Tiny 8pt

**Comment by IBBoard** [comment]
Which of your fonts is set to 8pt? Do you use any other GTK apps? What font size are they showing? Your case sounds like it could be KDE having bad default fonts for GTK apps, which should be configurable.

**Comment by chriztheanvill** [comment]
mmm, I think I do not use gtk apps. I will check the gtk default fonts.

**Comment by karafior** [comment]
> same issue when i tried corebird years ago, you can try this. change number to suit your display.
> env GDK_SCALE=1.3 GDK_DPI_SCALE=1.3 CLUTTER_SCALE=1.3 cawbird

That's a nice tip! Based on this, I adjusted my Flatpak installation with the following:
```console
flatpak override \
  --user \
  --env=CLUTTER_SCALE=1.3 \
  --env=GDK_DPI_SCALE=1.3 \
  --env=GDK_SCALE=1.3 \
   uk.co.ibboard.cawbird
 ```

**Comment by Brog33** [comment]
Cawbird sure has a tiny font size compared to my other Gnome apps. If I increase the font size in Gnome Tweaks, it helps, but the other Gnome apps get too large fonts :D

Wouldn't mind a font size setting in the config instead of bugging with the env vars.

**Comment by IBBoard** [comment]
Can anyone provide screenshot comparisons of these "tiny" fonts, and which themes they're seeing it in, because I'm really not seeing it.

Side by side comparison of Cawbird text and a label in Gnome Tweak Tool (selected using the GTK debugger and both zoomed to maximum size to make comparison easier):
![FontSizeComparison](https://user-images.githubusercontent.com/388582/104096308-ac573a80-5293-11eb-9345-fab0896f5b3a.png)

The height of every single letter is identical. The top of the "i", the top of the "t", and the bar of the "t" and the height of other letters.

Font size for labels in Cawbird - 13.3px Noto Sans Regular (set to 10pt in Tweak Tool):
![Screenshot from 2021-01-09 15-57-52](https://user-images.githubusercontent.com/388582/104096426-d3ae0780-5293-11eb-8244-d56a3204ef11.png)

Font size for labels in Gnome Tweak Tool - 13.3px Noto Sans Regular (set to 10pt in Tweak Tool):
![Screenshot from 2021-01-09 15-58-07](https://user-images.githubusercontent.com/388582/104096562-df013300-5293-11eb-9c9a-49de0dcf3a76.png)

We have no custom styling for font sizes. Everything about font sizing is managed by GTK and the themes.

**Comment by karafior** [comment]
In my case it's just a matter of preference. Generic interface fonts can be of "regular size", however contents from websites and such I simply like a bit larger.

Also, with the minimalistic design and focus on contents (text), it makes Cawbird look better when maximized or when using in split screen scenarios.

**Comment by Brog33** [comment]
> Can anyone provide screenshot comparisons of these "tiny" fonts, and which themes they're seeing it in, because I'm really not seeing it.

That's mindblowing. The font just seems much smaller than it really is then :D
It did a similar comparision now, and I was sure I'd prove it was smaller, but it actually wasn't. It just seems like a jedi trick of the mind. Maybe it's because of the narrow line-height? Idk.

However, when one click on a tweet, the font size in the item view is perfect and it would be great to have the option to use this size in the feed view.

**Comment by IBBoard** [comment]
I've looked at how the "Tweet Info" (single tweet) page does it and it uses a "scale" property. That's going to be better and easier than playing around with CSS and the many potential styling collisions that that could entail!

**Comment by IBBoard** [comment]
Okay, that new commit adds a setting for font scaling. I've only put it on tweet and DM text so far because it feels like this is "make tweets easier to read" (whether for skim reading or for certain scripts) rather than "scale for accessibility". Also, I don't think we can control tooltip scale, which further reinforces the "not directly for accessibility" approach.

I assume most people will probably just use "Large" (1.2 times larger) but included "X-Large" (1.2² = 1.44) and "XX-Large" (1.2³ = 1.728) because they were there. I couldn't see a reason to give people the option to make the text smaller!


Normal:
![Screenshot from 2021-01-16 11-09-57](https://user-images.githubusercontent.com/388582/104810317-9abde780-57eb-11eb-9f88-5babd8a4d57f.png)

Large:
![Screenshot from 2021-01-16 11-10-19](https://user-images.githubusercontent.com/388582/104810316-9abde780-57eb-11eb-8bea-74abbc7c052f.png)

X-Large:
![Screenshot from 2021-01-16 11-10-31](https://user-images.githubusercontent.com/388582/104810315-9a255100-57eb-11eb-8726-b9c3d7142b1b.png)

XX-Large:
![Screenshot from 2021-01-16 11-11-13](https://user-images.githubusercontent.com/388582/104810313-998cba80-57eb-11eb-8a04-5f8eb3096fd5.png)

**Comment by Brog33** [comment]
Just a mention: I switched from the Snap build to the Flathub one, and although it is the same version (1.3.2) the default font is larger and the "like" icon is not garbled. Also doesn't seem to suffer from the handshake issue YAY!

**Comment by IBBoard** [comment]
The handshake issue is known (#9) and not us and the Snap package needs to fix it, but the change in font size is odd (although not unexpected when you sandbox an app away from too many desktop settings) and I don't know why there would be a garbled icon are odd when it's an SVG that we package.

But most of that isn't related to giving people font size scaling options.

**Comment by IBBoard** [comment]
Closing this because I think it's done and no-one has said that I missed anything after the screenshots.

**Comment by mfreeman-xtivia** [comment]
Has this setting made its way to the release channel yet?

I pulled down the 1.3.2 DEB and I do not see any setting available for font sizes anywhere in Settings. Have scoured both the app and dconf-editor just to be sure

**Comment by IBBoard** [comment]
1.3.2 was released on 11th January. The last commit for this was on 16th January. So no, it's not released yet 😉

**Comment by mfreeman-xtivia** [comment]
Any ballpark thoughts on when 1.3.3 might be released?

**Comment by IBBoard** [comment]
I had planned to release last week, but one of our translators then found several holes in the translations. Once those are fixed then there will be a new release.
