### ISSUE TITLE
How to (automatically) build with key and secret

### ISSUE THREAD

**Issue by CodedOre** [IBBoard/cawbird#333]
So, while doing a testbuild (flathub/uk.co.ibboard.cawbird#5) for our translating bug with flatpaks (#297), I run into the problem that a new build now requires copying two files before being able to build it.

For flathub, this can be resolved by switching the cawbird module from the `meson` to the `simple` buildsystem, where we then can specify the copy commands before building:

```json
{
	"name":"cawbird",
	"buildsystem":"simple",
	"sources":[
		{
			"type":"git",
			"url":"https://github.com/IBBoard/cawbird.git",
			"tag":"some-release"
		}
	],
	"build-commands": [
		"cp data/consumer_k.example.dat data/consumer_k.dat",
		"cp data/consumer_s.example.dat data/consumer_s.dat",
		"meson --prefix=/app --buildtype=plain build",
		"ninja -C build install"
	]
}
```

However, I question if something like this is possible on OBS (not familiar with it, so maybe it is), but anyway, the question here is mainly: Would it make sense to make the keys an buildoption (at least additionally), so we can just define these in automated builds?

**Comment by CodedOre** [comment]
Another option for the flathub build would be to create a patch file and adding it to the build system.

So, three option, which will it be?

**Comment by IBBoard** [comment]
I've not configured it yet (I only run Git Master locally, because it's Git Master and therefore not guaranteed to be stable!) but this should be trivial for pretty much any build system. That's probably because every other build system is as flexible as Flatpak's "simple".

For example, Ubuntu 18.04 is old and chokes on Unicode, so we've got a work-around ([line 20](https://build.opensuse.org/package/view_file/home:IBBoard:cawbird/cawbird/debian.rules?expand=1)) while CentOS has an ageing gcc and needs extra arguments ([line 120](https://build.opensuse.org/package/view_file/home:IBBoard:cawbird/cawbird/cawbird.spec?expand=1)). But the main build is still all standard macros ([lines 122, 124 and 127](https://build.opensuse.org/package/view_file/home:IBBoard:cawbird/cawbird/cawbird.spec?expand=1))

I had assumed people would be able to supply their own files (trivial in RPM and DEB spec files) or run the copy command (fallback). But a build option would be quite a neat way to do it as well.

**Comment by CodedOre** [comment]
> I had assumed people would be able to supply their own files (trivial in RPM and DEB spec files) or run the copy command (fallback). But a build option would be quite a neat way to do it as well.

Well, as flathub builds the package automatically we need to provide a way in advance. Supplying a seperate file with a patch file should be easily doable, same as running copy. I have seen it with a build option with Newsflash. But I think a simple patch file should be the best approach...

**Comment by IBBoard** [comment]
I'll implement build options anyway. It's easier for people to put options/switches in a build rather than create a correctly formatted patch file.

**Comment by IBBoard** [comment]
Or maybe I won't. I'm struggling to see the Meson version of "Put this string (and nothing more) in this file". `configuration_file` seems to assume a specific format, while `custom_target` and `generator` assume a command to run. Newer meson has a `read()` function but a) that requires a modern Meson and b) there's no write.

**Comment by IBBoard** [comment]
Well, that was painful and ugly. But less painful and ugly that getting Meson to work with the "simple" input files approach.

I'll try to test the builds on my OBS version later.

**Comment by CodedOre** [comment]
I have initiated an testbuild for flathub as well.

**Comment by IBBoard** [comment]
My [custom build](https://build.opensuse.org/package/show/home:IBBoard:desktop/cawbird) on OBS [seems to have worked](https://build.opensuse.org/public/build/home:IBBoard:desktop/openSUSE_Tumbleweed/x86_64/cawbird/_log), so I'll assume this is okay for other build platforms now.

**Comment by fickludd** [comment]
> [Edit] Seemingly the answer is "do trivial and obvious stuff with a custom Python script rather than built-in functions or existing command-line tools" - [mesonbuild/meson#512](https://github.com/mesonbuild/meson/issues/512)

I though the same, but then I found that there is nowadays a `capture` option in `custom_target` which solves exactly this problem. https://mesonbuild.com/Reference-manual.html#custom_target

**Comment by IBBoard** [comment]
I'm sure it's useful. But I'm not sure that would fix this specific situation.

With the file-based approach, we 'just' needed Meson to write a string to a file. `echo $var > file` would do that. But it's an external call and not as portable. And I hit problems with writing to a specific output directory (because parts of Meson want files, not paths so that people don't assume certain run directories).

I think I tried it and never got anything useful. I'm not even entirely convinced that I got it to run at all.

But it might solve some other issues for other people.
