### ISSUE TITLE
Thread tweets should be easy to see in the timeline

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#339]
The normal 'Replying to XXX' line doesn't appear when an tweeter replies to his own tweet, so I can't tell if its a new tweet or a threaded tweet.
![image](https://user-images.githubusercontent.com/4412114/111056009-f8417e00-8494-11eb-85df-e4c00f639063.png)

**Comment by IBBoard** [comment]
It's intentionally on the timelines to reduce visual noise. That's why we've got the "is a reply" icon on the top-right corners.

If that's not clear enough for people then we'll have to consider it in the redesign.

**Comment by philipzae** [comment]
Guess I missed the icon as an indicator, also doesn't have a tooltip, as I only look up in that corner when i need to click or copy the link.

**Comment by CodedOre** [comment]
I think we could do something similar as with #307, basically to put a notice in the same place as where we will place "This tweet was retweeted".

The obvious question is how to design it in a good way...
Twitter does display "Replying to <insert name here>" and I think that would be necessary to avoid confusion with a similar label.

**Comment by IBBoard** [comment]
Twitter only puts the "Replying to" line in when it breaks the thread. If it can show multiple tweets in a thread then it shows the line and shows them out of pure chronological order (compare tweets two and three here)

![Screenshot_2021-03-21 IBBoard ( IBBoard) Twitter](https://user-images.githubusercontent.com/388582/111912572-29f0b100-8a62-11eb-93aa-a7b895f0110c.png)

If the "replying to" is under the name (like we do for everyone else who gets mentioned in replies) and put the RT at the top then *hopefully* it's not too confusing.

Thinking about it, it probably makes sense as well. The RTed and Liked icons in the top-right are your interactions with that tweet, but the "Replies" is about the tweet itself. IIRC Baedert removed it and I put it back in my own builds (and then Cawbird), because I'm used to seeing it.
