### ISSUE TITLE
Can't cancel a reply to the tweet

### ISSUE THREAD

**Issue by ValdikSS** [IBBoard/cawbird#340]
**Describe the bug**
If "reply to tweet" button is pressed but the tweet is not sent, it's not possible to cancel reply to that tweet. If "reply to tweet" window is closed and regular "compose tweet" button is pressed, the tweet for which "reply to" button was pressed is shown. This behavior persists even after restarting the program.

**To Reproduce**
1. Press "reply to tweet" button on any tweet in the timeline
2. Close the window without writing the tweet
3. Try to compose new tweet, without mentioning "reply to" tweet.

**Expected behavior**
Compose new tweet window does not show "reply to" tweet.

**Screenshots**
Please watch the video.

https://user-images.githubusercontent.com/3054729/111899116-88eeff80-8a3b-11eb-83c7-6cfa5f7379a9.mp4

**System details:**
 - OS: Fedora 33
 - Version: cawbird-1.3.2-6.66.x86_64
 - Package type: Official RPM

**Comment by IBBoard** [comment]
This is intentional to 1) keep tweet content in case it fails to send (network errors etc) and 2) allow you to keep a draft tweet. We store it in the database, hence why it persists beyond restarts.

If you don't want the draft, delete the content and it will also forget the tweet that you're replying to.

**Comment by CodedOre** [comment]
Actually, Twitter does also keep drafts of an written reply or tweet, just only inside the scope it would be placed in.

That might be something we could do?
It would increase complexity, and of course we need to ask our self to which extend we keep drafts (one tweet and one reply maybe?).

**Comment by ValdikSS** [comment]
>If you don't want the draft, delete the content and it will also forget the tweet that you're replying to.

Oh thanks, indeed, but that's not intuitive at all. Could it be better to make explicit "clear" button to remove reply to post from the compose interface?

**Comment by IBBoard** [comment]
"I don't want this, therefore I will delete it" seemed reasonably intuitive. Maybe it would be clearer if it was "Close" rather than "Cancel".

I'm not sure we could do a "Clear" button without it cluttering up the UI.

The other options are:
1) Prompt on load - "Do you want the draft?"
2) Prompt on close - "Do you want to keep this?"

I hadn't implemented either because it felt like most people wouldn't leave half a tweet unless they wanted to keep it.

**Comment by ValdikSS** [comment]
"Remove the text to clear the draft" fine print somewhere near text field is fine too.

**Comment by IBBoard** [comment]
I think that would still be a bit messy. And if you have to annotate your UI like that then it's a good sign that something is wrong with your usability.
