### ISSUE TITLE
Force refresh/reload

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [IBBoard/cawbird#396]
Feature request: an 'Force refresh/reload'-button or similar functionality.

This feature would be very useful for cleaning out removed tweets. Also, occasionally some pictures refuse to load unless Cawbird is restarted.
Because of those issues I find myself being forced to restart Cawbird from time to time, which is not very user-friendly.

**Comment by IBBoard** [comment]
We've had a reload button for images since v1.4 ([commit](https://github.com/IBBoard/cawbird/commit/10fdf98f9d93b869f14d7293d55904c30f58ab47)) so if an image fails to load and you can't refresh it then that's a separate bug.  Or if reloading doesn't reload it and it only loads when you restart (which could also just be timing and network issues). Please run Cawbird from a terminal and include any warnings in a new ticket when it next happens.

As for old tweets, we already clean them out whenever you scroll to the top of a feed. If there's a specific case where it's not cleaning out old messages then I need more details about your settings and situation (auto-scroll or not? high volume of tweets or occasional?).

**Comment by cyberpunkrocker-zero** [comment]
> As for old tweets, we already clean them out whenever you scroll to the top of a feed
That does not work. Just a few minutes ago a guy I was following tweeted something with a video, made a typo, deleted the tweet and tweeted again. Nothing I could do removed the deleted tweet, until I restarted Cawbird. "...scroll to the top of a feed" well those two tweets were already the two top tweets. Autoscroll is enabled.

**Comment by IBBoard** [comment]
Ah, that kind of "cleaning out removed tweets". Yeah, Twitter doesn't have an API for "tweet has been deleted" since they dropped streaming, so we can't detect that. We might be able to check the error codes when you try and interact with it, but that's about it.

Is it a frequent problem that people delete tweets and you want to reply to them/interact with them and then they're gone?

**Comment by cyberpunkrocker-zero** [comment]
It depends. Because Twitter does not allow editing of sent tweets, if you make a typo or something, the only way to fix it is to delete the tweet and try again. Sometimes it happens a lot, sometimes doesn't... cannot really say anything about the frequency.

**Comment by cyberpunkrocker-zero** [comment]
It is problematic when the tweet includes a picture or a video. You try to see it and "Oh, it is gone already..."

**Comment by IBBoard** [comment]
Except that we simulate streaming mode by [only getting tweets since the last one](https://github.com/IBBoard/cawbird/blob/master/src/CbUserStream.c#L363-L377) (with some adjustments for eventual consistency), so we don't get a full set to compare.

We could do more overlap (e.g. always just getting "the latest" tweets), but a) it's wasteful for people on limited bandwidth (no new tweets = 200 redundant tweets!) and b) it will cause more problems for people who have rapidly changing timelines.

We could increase the overlap to a few minutes to catch more people, but if we set it to two minutes then it won't catch the tweet reposted after five, and if we set it to five then it won't catch the one done after ten, and…
