### ISSUE TITLE
show DM message reactions

### ISSUE THREAD

**Issue by rorymobley** [IBBoard/cawbird#423]
i tried searching open and closed issues for this and didn't find it, but forgive me if this is a dup. 

**Is your feature request related to a problem? Please describe.**
people may react to a DM you've sent and you wouldn't know it

**Describe the solution you'd like**
hopefully attach icons of reactions to their messages(thumbs-up, heart, thumbs-down)

**Comment by CodedOre** [comment]
Unfortunately, it seems that Twitter does not provide an API for that, so it's not something we could implement.

They may provide an option when the v2 API will get direct message endpoints, but we'll have to see.

**Comment by IBBoard** [comment]
We'll keep it on the list (at least to display them - inputting them could be tricky because of the need for graphics and keeping in sync). But as CodedOre says, Twitter hates third-party clients and doesn't give us a fully-featured anything so that they can stop us fixing all of the annoyances in their UI and driving people away from the web 🙂
