### ISSUE TITLE
Set focus on the editor after choosing an emojy

### ISSUE THREAD

**Issue by Nardol** [IBBoard/cawbird#427]
**Is your feature request related to a problem? Please describe.**
When redacting a tweet or a private message, after I have chosen an emoji, it looks like the emoji button still has the focus and I have to brows again to use the editor again.

**Describe the solution you'd like**
After choosing an emoji, it myght be reasonable to return to the editor to continue writing.

**Describe alternatives you've considered**
I don't see any, for now sometimes I find the right arrow to be again on the editor.

**Additional context**
After inserting an emoji, tipically we want to continue typing, except if we want to insert a list of emojis.

**Comment by IBBoard** [comment]
As we close the emoji list when you select an emoji then it would make most sense to focus the text input box, rather than changing the behaviour to keep the list open. Keeping it open would let people add multiple emoji in a row more easily, but would be more work when you just want one smiley at the end 🙂

**Comment by IBBoard** [comment]
No, it's fine, I understood 🙂 I was just confirming the thinking that focussing the text box was more sensible than changing the behaviour to keep the emoji list open.
