### ISSUE TITLE
Work through Tor .onion Twitter domain

### ISSUE THREAD

**Issue by j1warren** [IBBoard/cawbird#440]
Since Twitter introduced Tor .onion address, can Cawbird use it?
Probably should check if Api domain/endpoints are accessible through .onion.

**Comment by CodedOre** [comment]
The answer is: Very likely not.

The first question is if the API endpoints are exposed, which I doubt but will check.
However, the more important question is: How to connect from our client to this endpoints? Would we need additional dependencies or can this be done in a way that is relatively manageable?

**Comment by j1warren** [comment]
Tor provides SOCKS proxy, so implementing generic SOCKS support (with DNS resolvinf through the same proxy) should suffice.

**Comment by CodedOre** [comment]
The thing is that we're using the `librest` library to make most of the calls, as this implements certain functionality for us.

If `librest` would not support this SOCKS proxy, we would need to reimplement the features provided by this library, where the cost-benefit calculation quickly topples.

I'm going to check today if it could be done with `librest`, but again, it probably will not.

**Comment by CodedOre** [comment]
So, have done some checks, and it does not seem like there is an publicly available onion adress for Twitter's API.

Twitter itself [lists three addresses](https://help.twitter.com/en/using-twitter/twitter-supported-browsers): The main site, an proxy for media and one for their url shortener. I checked if I can call API endpoints from these with no success.

So, apart from being difficult to implement, it's also not possible without endpoints.

**Comment by IBBoard** [comment]
Thanks for looking in to this, @CodedOre.

One question: What's the benefit of using the Tor URLs over using the normal URLs over Tor? If you run Tails then your network traffic is already run through Tor, and it's the same service as public Twitter so a local oppressive regime can't see what you're browsing, your connection comes out in another country, and you're  basically as safe if you go to https://twitter.com (because HTTPS protects you from last hop interception attacks).

There isn't even a benefit in a narrower situation like using just a Tor Browser (rather than a whole distro) where I can see it helping. If the Tor Browser is sending twitter.com over clearnet and twitterblah.onion over Tor then that's a HUGE risk and vulnerability for people to include random clearnet stuff in darknet sites and correlate behaviour! (Or accidentally giving themselves away by entering twitter.com rather than the un-memorable Onion address)

**Comment by j1warren** [comment]
> What's the benefit of using the Tor URLs over using the normal URLs over Tor?

There are places where twitter is blocked. Tails is an inconvenient overkill for such cases.

**Comment by CodedOre** [comment]
About proxies:

Just stating this with "as far as I know", but `libsoup`, which `librest` uses to call the endpoints, has support for proxies, and defaults to the one set in the network settings.

So technically, it should be already implemented.

**Comment by IBBoard** [comment]
Tails is Debian-based, so in theory it should be possible to test it with one of the Debian packages (and if it uses a new enough base Debian distro then it might be in the system repos rather than needing the Open Build Service one)

And if it does work then you can presumably use environment variables when launching it, if you do have some kind of (risky, insecure) split environment.

**Comment by CyberTailor** [comment]
Please implement proxy support for countries where Twitter is blocked

**Comment by IBBoard** [comment]
As CodedOre said, Cawbird uses librest for its HTTP connections. I've just checked and Cawbird (via librest) honours the proxy settings configured in `gsettings` (which Gnome Settings will configure). I've not worked out an equivalent to the `http_proxy` environment variable that it supports.

**Comment by IBBoard** [comment]
I've not tested with Tor, but `https_proxy` seems to work as does `gsettings` config, so unless someone can provide more specific details about how Tor's socks proxy differs and why it doesn't just natively work via librest then I'll assume that it is all okay.
