### ISSUE TITLE
Request for ARM64/ARMhf OBS releases on Ubuntu 18.04

### ISSUE THREAD

**Issue by theofficialgman** [IBBoard/cawbird#458]
**Is your feature request related to a problem? Please describe.**
Nvidia jetson products are quite numerous and use ubuntu bionic 18.04 as the OS.

**Describe the solution you'd like**
Add arm64 and armhf ubuntu 18.04 targets to the OBS repo

Yes I have previous asked for debian 11 and users on the pis have been using that since you enabled it.
thanks you.

**Comment by IBBoard** [comment]
Unfortunately, it looks like openSUSE Build Service doesn't have system packages/images for anything other than i586 and x86_64, so we can't support them.

https://build.opensuse.org/project/show/Ubuntu:18.04

Strangely, I can't find anyone talking about it at the moment.

**Comment by theofficialgman** [comment]
that very strange... they has it on older ubuntu releases and newer ones as well
for example: 14.04 https://build.opensuse.org/project/show/Ubuntu:14.04

**Comment by theofficialgman** [comment]
@IBBoard we were looking in the wrong place
here it is. its under the ports because non amd64/x86 are in ubuntu ports
https://build.opensuse.org/project/show/Ubuntu:18.04:Ports

**Comment by IBBoard** [comment]
Ah, great find! I'd tried searching for "Ubuntu" projects and the ports hadn't shown up in the lists. Loads of old and EOLed versions of Ubuntu or people's personal Ubuntu projects, but not the ports.

Looks like I should have typed "Ubuntu:18" rather than just "Ubuntu" and assumed it wasn't there because of all of the personal projects 😄

Just enabling it now.

**Comment by IBBoard** [comment]
Should be built and available shortly (both Cawbird and Unstable)
