### ISSUE TITLE
YA problem with cawbird on venom linux ...

### ISSUE THREAD

**Issue by bja-au** [IBBoard/cawbird#461]
G'day again,

When I start up cawbird I am getting the following ...

bash-5.1$ cawbird
libva info: VA-API version 1.15.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1

... however all appears to be going ok except that after a while I get no media (pic or vids) and the following logs ...

(cawbird:24802): Gtk-WARNING **: 13:11:53.537: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(cawbird:24802): Gtk-WARNING **: 13:11:53.537: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

... Any ideas please?

Thanks

Oh and also cawbird hangs :(

**Comment by IBBoard** [comment]
Looks like `libvaapi` (possibly just `libva` on Ubuntu) is either incorrectly configured or broken on your system. It's optional video optimisation support that (IIRC) is only relevant for some systems. `iHD` and `i965` in the file names suggests that it's trying to load drivers for Intel APUs/GPUs.

The negative sizing is presumably because the graphics optimisation screws up the loading of the content and so we get invalid dimensions back.

**Comment by bja-au** [comment]
Thanks for that info - will pass to those more knowledgeable than I :)
