### ISSUE TITLE
Please update hungarian language file

### ISSUE THREAD

**Issue by ViBE-HU** [IBBoard/cawbird#465]
AFAIK the project using the Transifex translations actively. About a month I translated a bunch of strings but it's still not present in the Github repo. Isn't it automatized by a bot?

**Comment by IBBoard** [comment]
Huh. It should be automated with a bot that makes a pull request. But since March [we've only had Spanish updates from Transifex](https://github.com/IBBoard/cawbird/pulls?q=is%3Apr+Translate).

Transifex shows the [last updates on 5th March 2022](https://www.transifex.com/cawbird/cawbird/language/hu/).

I'll investigate. Maybe I need to set something up on this end for Transifex to bother submitting the PR. Or I can just download and upload the file.

**Comment by ViBE-HU** [comment]
Yeah, that's why I here now. I'm not in a hurry but would be good to see the changes and I don't get the bot's logic. Pretty strange.

**Comment by ViBE-HU** [comment]
I'm not in a hurry but any news?

**Comment by IBBoard** [comment]
Sorry, I've not had much time to look at Cawbird since moving house.

According to Transifex, there's still 50 strings that haven't been translated. If they don't have a direct translation and you'd use the existing text then it still needs to be copied across as the "translation".

The only thing that I can see is that the French and Spanish translations (the last two to get a PR) completed the translation to 100%. But I thought we'd had notifications for less than 100% coverage before. Maybe I'm wrong. I'll see if there's a setting that I can change.

**Comment by IBBoard** [comment]
Ah, looks like it will submit when you hit 100%, and then submit every time that you make a change after that (if I'm reading it right) 🙂

![image](https://user-images.githubusercontent.com/388582/196252683-2b36c337-02d2-4e08-85b2-553d9d2d1e1f.png)

I've forced a manual sync of all languages with over 85% coverage.

**Comment by ViBE-HU** [comment]
It would be nice if you remove this limitation. I would translate all strings but some needs more explanations since the context is not clear. I cannot figure out where Twitter use those exactly. That's why undone.

**Comment by IBBoard** [comment]
Unfortunately the only options are "push to GitHub when 100% translated" or "don't push to GitHub and make it a manual task" (which is a very noisy process because gettext and Transifex format things slightly differently, and Transifex loses any existing contributor history).

If you've got any questions about translations and context then you can use the "Comments" section and the "Add Issue" button the the bottom-right of the translation and I'll get notified about it.

![image](https://user-images.githubusercontent.com/388582/196263618-42ab6a01-fe24-4857-956f-0810235495a7.png)
