### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by giovannicaligaris** [IBBoard/cawbird#67]
Like most new GNOME apps, if you can please add a dark theme.

Thanks

**Comment by IBBoard** [comment]
Cawbird already has a dark theme via Adwaita Dark. Revision 07043c28 makes it more consistent with the theme.

I've not seen "dark themes" in most apps unless they have a "night mode" approach.

**Comment by giovannicaligaris** [comment]
I meeant to say dark/night mode. Rhythmbox has it and a few other gtk apps.

**Comment by IBBoard** [comment]
Gnome Books/Documents has a "night mode" that affects the whole app, but their focus is for reading long document. Evince has a night mode but it only affects the document and not the UI. Image Viewer (eog) has nothing but dark and Shotwell has a "dark theme" option but they're both image apps and people seem to like dark UIs with their image apps. Ditto GIMP. 

Meanwhile, Dictionary doesn't, Nautilus doesn't, Characters doesn't, Fonts doesn't, File Roller doesn't, Settings doesn't, Brasero doesn't, Sound Juicer doesn't, Calculator doesn't, Seahorse doesn't, System Monitor doesn't, and GEdit doesn't*. And that's just the apps that I have installed (which I *think* are all Gnome apps).

I can't find a dark/night mode in Rhythmbox.

\* GEdit has colour schemes for the edit pane, but not the UI

**Comment by IBBoard** [comment]
There are currently two options for people who want a dark mode:

1) Change the system theme through Gnome Tweak Tool and Cawbird honours it
2) Run Cawbird as `GTK_THEME=Adwaita-dark cawbird` to explicitly set the theme* (other theme names may be necessary on, for example, Ubuntu)

\* The old approach was "Adwaita:dark" to request the dark variant, but this has since been deprecated as an approach
