### ISSUE TITLE
pin code for twitter? what is that?

### ISSUE THREAD

**Issue by boistordu** [IBBoard/cawbird#73]
Hi,

So what's this famous pin code that you are asking at launch on cawbird? To register a new account with the app I mean. 
there is nothing about that in the twitter help, nothing on any search engine with twitter.com and pin code as key words and you obviously don't provide a link on the welcome screen. Inever heard anything about a pin code... Could you clarify please?

**Comment by IBBoard** [comment]
The PIN is part of the OAuth authentication process that lets Cawbird post using your account ([developer docs](https://developer.twitter.com/en/docs/basics/authentication/oauth-1-0a/pin-based-oauth)). Twitter explains the OAuth process a bit in [their help centre](https://help.twitter.com/en/managing-your-account/connect-or-revoke-access-to-third-party-apps) but doesn't go in to details about the PIN.

Cawbird does the OAuth by opening your default browser when you press "Request PIN". You then need to log in to Twitter, approve the app, and copy the PIN that Twitter gives you back into the Cawbird dialog box.

Cawbird uses the "log in through your browser and get a PIN" approach because asking for username and passwords directly is a Very Bad Thing™ and Twitter used to prohibit the use of an embedded browser in third-party apps on the basis that you can then sniff the username and password.

If you pressed the Request PIN button and didn't get a browser window opening up with a URL like `https://twitter.com/oauth/authorize?oauth_token=…` then there is most likely something wrong with your default browser setup.

**Comment by boistordu** [comment]
okey now I found the information. And now I understand why you didn't put any link. 
But we might have a bug because the snap version of your version of cawbird isn't opening a firefox window under fedora 31 workstation.
I don't see how on a fresh install it would fail un less it has to do something with the snapd bug from fedora 31 at the moment? [forum page](https://forum.snapcraft.io/t/how-to-fix-snap-binaries-not-found/9469?page=2)
```
(cawbird:23603): cawbird-DEBUG: 04:00:19.328: AccountCreateWidget.vala:64: Trying to open http://twitter.com/oauth/authorize?oauth_token=
user-open error: cannot find snap for connection: cannot find a snap for pid 23676
```

**Comment by IBBoard** [comment]
This is why I use native builds!

From a quick look then I don't know enough about Snap to tell whether that forum post is the problem, but as a general developer then it doesn't quite look the same.

The Snap package is a community package, though.  You'll have to ask the maintainer.
